# Chinook Jargon {.unnumbered #sec-chinook-jargon}

That Thomas Russell communicated with the majority of Haida through the language ‘Chinook Jargon’ is evidenced by the following quotes in his diary:

[**Tuesday 8th  November 1870**](diary_Volume_1.qmd#sec-appendix-1-8-11-nov)

>"He speaks Chinook very indifferently. When speaking of himself, he always uses the first person pronoun both in English and Chinook (Nika, me): I presume he thinks he cannot express it too clearly so he gives both."

[**Tuesday 29th November 1870**](diary_Volume_2.qmd#sec-volume-2-29-nov)

>"I get along very well with Skidegate as he speaks Chinook pretty fluently, but good-natured little Scotchguy talks away for an hour, and I am just as wise as when he began. He jumbles up Hydah Chinook and English in such a way that I often wonder if he knows himself what he is talking about. When I think he is talking about anything of importance, I get someone to interpret."

Scattered through Russell's diary are the following Chinook Jargon words, the english translation for which is provided here:

#### cultaz potlatch {#sec-appendix-cultaz-potlatch}

**Also spelled:** Cultas Potlatch
**Dates of useage:** Sunday 27th November 1870; Sunday 29th January 1871; Tuesday 7th March 1871;
**Meaning:** A gift with no reciprocal obligation expected. 

#### hyassclosh {#sec-appendix-hyassclosh}

**Date of useage:** Tuesday 7th February 1871;
**Though written as one word by Russell, this is probably two words: **
hyass meaning important closh (Russell spelling - which in the dictionary is kloshe or kloose) meaning good, correct or right.
**Meaning:** Though the meaning is not readily apparent, taken together these two words aseemingly signify something like ‘important and right to do’.

#### Iktas

**Dates of useage: **Sunday 27th November; Sunday 29th January 1871;
**Russell translation:** Goods

#### Keeysly 

**Dates of useage: **Sunday 6th November 1870;
**Russell translation:** officer in charge

#### Klootchman {#sec-appendix-klootchman}

**Dates of useage:** Wed 12th October 1870; Monday 28th November 1870;
**Meaning:** A woman or 'female" (of anything). 
**Note:** Although the modern Chinook Jargon dictionary states that word 'klootchman' today is not derisive, it was considered either derisive or demeaning by Captain Gold and his wife – and was meant to be so by Russell.

#### Muckmuck {#sec-appendix-muckmuck}

**Date of useage:** Sunday 13th November;
**Meaning:** Food.
**Note:** According to the dictionary this word is actually ‘muck-a-muck’

#### Siwashes {#sec-appendix-siwash}

**Dates of useage:** Saturday 29th October; Monday 28th November; Friday 16th December; Sunday 15th January 1871; Sunday 12th February; Tuesday 14th February;
**Meaning:** A First Nations man, but sometimes used for women as well.
**Note:** The origins and meaning may be considered pejorative and derogatory French sauvage (savage). Russell at times used it in a derisive way, but not always. 

#### SucKally Tihee {#sec-appendix-suckally-tihee}

**Dates of useage:** Tuesday 14th February 1871;
**Meaning:** God.
**Note:** Russell’s spelling differs from that of George Gibbs’ Dictionary of the Chinook Jargon which spells it Sagh-a-lieTyee

#### Tihee {#sec-appendix-tihee}

**Date of useage:** Sunday 15th January 1871;
**Meaning:** Chief

## References

Gibbs, George. 1863. Dictionary of the Chinook Jargon, or, Trade Language of Oregon [Abridged].  
Chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.washington.edu/uwired/outreach/cspn/Website/Classroom%20Materials/Curriculum%20Packets/Treaties%20&%20Reservations/Documents/Chinook_Dictionary_Abridged.pdf

Chinook-English Dictionary
https://www.translationdirectory.com/dictionaries/dictionary037.php

Wikipedia: Chinook Jargon
https://en.wikipedia.org/wiki/Chinook_Jargon