---
editor: 
  markdown: 
    wrap: sentence
---

# Volume II {#sec-volume2 .unnumbered}

## Monday 28th of November 1870 (continued) {#sec-volume-2-28-nov}

The following is a copy of a paper given by me to Captain Gold.

>The bearer Captain Gold (a native of Gold Harbour and chief of a portion of that Tribe) is a most unmitigated rascal; he is eternally on the “make”, and continually seeking to allure the unwary into the belief, that he is a great chief, and of a most kindly disposition.
>
>The King George Men (as he terms the whites) he asserts are his friends, and that he will always guard them against danger from other Indians. The scoundrel does this in order to enlist the sympathies of those who don't know him, and to wring out of you all that he can.
>
>You may then go to the devil for aught that he cares, until his unsatiable thirst for begging prompts him to return, when he will attempt to twist that cut-throat countenance of his into (what he thinks) the semblance of the very essence of purity, but Ah! Beware! for he is an oily dog. He takes a great pride in presenting his papers to all newcomers, and at such times puts on a most majestic air and expects you to pull off your coat and give it to him, for the good character he bears through the medium of these papers.
>
>Since it has been customary upon such occasions to acknowledge his good qualities by a potlatch, give him a “quid” of tobacco; at the same time impress him very forcibly that you give it to him not because he requires it, but simply because he is such a good man (“over the left”).
>
>In speaking to him of his worthy spouse, you must be very careful not to hurt his dignity by calling her a Klootchman; it appears that someone has impressed him with the idea that he is a King, and of course as a necessary consequence his wife is a Queen; you must therefore make mention of her as his wife or Queen Gold!!!
>
>Thomas Russell Superintendent Queen Charlotte Coal Mining Company P.S. I have unwittingly been very remiss.
Amongst the Captain’s good qualities there is one which I have omitted viz; that he is not by any means a thief: he only appropriates for his own use anything that he can lay his hands upon.
>
>He does this in a very delicate manner, always taking great care that he is not observed by the other Indians. He will tell you that he is not the same as other Indians, that is to say he does not lie nor steal (what a liar!) not even prowl about at night, but he boldly asserts that the other Indians are like dogs, continually prowling about at night to see what they can pick up.
>
> \- TR

## Tuesday 29th of November 1870 {#sec-volume-2-29-nov}

Only had one shower of rain today.

High busy with the road, the miners have been timbering up the fault in the mine all day.
Had a visit from Captains Skidegate and Scotchguy this evening; I get along very well with Skidegate as he speaks Chinook pretty fluently, but good-natured little Scotchguy talks away for an hour, and I am just as wise as when he began.
He jumbles up Hydah Chinook and English in such a way that I often wonder if he knows himself what he is talking about.
When I think he is talking about anything of importance, I get someone to interpret.
I questioned them about the powder that was stolen from Robinson's house, but of course they knew nothing about it.

## Wednesday 30th of November 1870 {#sec-volume-2-30-nov}

Showery today.

Road making in this kind of weather is not very enviable, it is just like working amongst so much mud.
About 6:00 o’clock this morning whilst I was in bed, and half awake, I heard a small familiar voice call “Pa”.
I jumped up with a start, but no one was near.
I assuredly heard that voice, and the more I think of it, the more plain it appears to me.
I am not much of a believer in such things, but I sincerely trust “the loved ones at home” are well.
This is Saint Andrews Day.
As I write I wonder who the Caledonians have chosen for their president.
I hope they have been true to themselves and put the right man in the right place, but I fear they will have been all sixes and sevens and put the wrong man in.
I would give a trifle to be amongst them tonight, but I am with them in spirit.
I will therefore clink in a cup of cold water Wives and Sweethearts.

## Thursday 1st of December 1870 {#sec-volume-2-1-dec}

This has been a beautiful day; the weather is exceedingly mild.

The miners have finished securing the fault in mine, and are now extracting coal again.
I am getting on very well with the road, but it is going to be a longer job than I thought for the extraction of the large root is quite a job of itself.
We have come upon a large boulder which only appeared a small stone protruding from the surface, but a little time and blasting powder will make it manageable.

## Friday 2nd of December 1870 {#sec-volume-2-2-dec}

It was very frosty this morning, Mount Seymour looked as though it had been clothed in gold.
It is something very grand to watch the rising sun light up these mountain peaks.
Today has been quite a treat, not a cloud to be seen.

The sun, however, only strikes on portions of the track; the high mountains and trees hide old Sol from us.
During the winter season the sun never shines on the house where we live (Trounce’s Cottage gets a little blink about 11:00 o’clock) .
This adds to the dreariness of the place, and from the incessant rains the houses are very damp.

The Indian dogs are a great nuisance; they are continually chasing and biting the pigs, in fact they killed one three days ago.
I warned the Indians about their dogs and told them if I saw any of them chasing the pigs I would shoot them.
They very cooly replied that if I shot the dogs they would shoot the pigs.
The Indians are too saucy by half: we sadly want a gunboat to give them a shaking up.
When I first arrived here I found the car standing with one wheel off, and upon inquiring why, Branch told me that he had to do so to prevent the Indians from pushing her up the track and then riding down in her.
They were in the habit of doing this after the men had gone to bed, and when he told them to desist they only laughed at him.

I ordered the wheel to be put on and kept on, at the same time telling the Indians that if ever I found them moving it from its place without my permission I would chastise them most severely.
Things went on all right until last night when I heard them moving her very cautiously up the track.
I rushed up onto the bridge and made for them, but they saw me coming and ran away like a lot of young deer.
I gave them chase and succeeded in capturing two.
They were only boys, so I gave them a good shaking and made them drag the car back to its place.
I had not been more than half an hour in the house when I heard her being moved again.
I went out and called to them to stop, which they did.
Four men had possession of her this time.
They stood by the car until I came up.
I collared the first fellow within reach, gave him a good shaking and boxed his ears.
When the others saw me let fly my fist at him, they ran away like so many cowardly dogs.
I made this fellow push the car back to its place and told him if I found any of them trying the like again I should take a stick to them.

## Saturday 3rd of December 1870 {#sec-volume-2-3-dec}

Fine all morning, snowing all afternoon; cleared up about 8:00 o’clock PM.

I expected to have had the road finished today, I did not think there was so much work in it until we had fairly began.
Two days, however, I think will finish it.
I will then alter the shute by putting in a small shute at the bottom of the screen, this will carry the coal to the bottom of the main shute, and prevent the coal from being smashed up.

## Sunday 4th of December 1870 {#sec-volume-2-4-dec}

This has been the finest day we have had for a long time.

Had our best cat worried by Indian dogs today.
I wish I had some subtle passion for these mangy curs.
I don't know what the company could have been thinking about when they allowed the Indians to locate here.
From what Beauchamp tells me they must have stolen nearly all the blacksmith and carpenter's tools: they even steal our firewood at night.

Went to see Mrs. Skidegate ‘s mother this evening to prescribe for a bad leg that she has.
I was perfectly horrified when I looked at it; it is almost rotten from the hip to the ankle, and has been in this condition for more than a year.
Gave her a piece of Castille soap, told her to wash it three times a day, also some Friars Balsam to dress it with.
I find that a great many of the Indians are afflicted in this way: one man in particular, his neck is in such a state that you would not be surprised if his head tumbled off some day.

:::{.callout-tip title="Medical Explanation"} 
See @sec-appendix-4-2-4-dec
:::

## Monday 5th of December 1870 {#sec-volume-2-5-dec}

Raining all morning, had quite a snowstorm this afternoon.

We could not work more than half a day on the road.

Laiken laid up today with a cold.
There is a strong current of air through the mine, which makes it very cold sometimes.
I feel very thankful that my own health has been excellent since I have been here: an occasional headache is the only thing I have had to complain of.
I sleep much warmer at night since I changed my bed.

## Tuesday 6th December 1870 {#sec-volume-2-6-dec}

This has been quite a fine day.

Beauchamp laid up with a cold, he has a bad cough.

We made good progress with the road today and unless it rains cats and dogs we will finish it tomorrow.
Laiken went to work this morning again, I wanted him to remain at home for a day or two, but he would not.
In a place of this sort one ought to be very careful to keep out of sickness if possible; no doctor to be called in, and the company loss the man's time.
Some men are such pigheaded fools, that they won't be advised.
I think by the time I return to Victoria I shall be quite a Quack in Medicine, what between the men and Indians I have a very fair practice.

## Wednesday 7th December 1870 {#sec-volume-2-7-dec}

Showering all day.
Finished road and made a great job of it, but it will never be secure until the face is cribbed from the bottom, which would cost about \$150.00 but it could be done cheaper and better in summer.

## Thursday 8th December 1870 {#sec-volume-2-8-dec}

Showery today, very mild. 

Measured the mine today, but could not ascertain the depth of the air shaft.
This shaft is put in in rather a peculiar way. It is sunk perpendicular to a distance of 30 feet from the surface, then it has an incline (but the length of this, I cannot say, it is very insecurely timbered the miners were afraid to walk up it) then it runs perpendicular again to the tunnel.The amount of ground worked by Robinson and Branch is as follows. Reckoning the average width of the seam of coal to be two feet 6 inches

| Length (ft) | Depth (ft) | Thickness (ft) | Cubic Feet |
|------------:|-----------:|---------------:|-----------:|
| 84          | 45         | 2.5            | 9,450      |
| 58          | 50         | 2.5            | 7,250      |
| 40          | 45         | 2.5            | 4,500      |
| 32          | 30         | 2.5            | 2,400      |
| **Total**   |            |                | **23,600** |

Reckoning 28 cubic feet to a ton this ought to have yielded tons 843.
From what I remember of Landale's report, I believe he stated that 500 tons of coal had been obtained in driving the tunnel.

He could not have measured the tunnel, nor the coal taken there from, or if he did he knew nothing about such things. From where they struck the coal up to the present manway (which is near to where the coal runs out ) is 300 feet long, height 7 feet 6 inches, average width of seam 2 feet 9 inches, making a total of 6187 1/2 cubic feet. Reckoning 28 cubic feet to a ton this would have produced 221 tons of coal - not one half of Landale's estimate.

The foregoing calculations do not allow anything for waste which is very considerable.

The result of these figures show that 221 tons were extracted in driving the tunnel, 843 tons by Robinson and Branch making a total of 1064 tons.

The amount of coal shipped to Victoria was 300 tons: the amount of coal here at present is 350 tons making a total of 650 tons. Since there has been sufficient ground worked to produce 1064 tons and only 650 tons represent it this shows a deficit of 414 tonnes or in other words a loss of that amount in the shape of waste - Nearly 2/5 of the whole.

This great waste I chiefly attribute to the coal and slate falling together in the mine and the coal being the softer substance it gets broken into small pieces. A great deal of it remains in the mine, and what does not come out is shoveled over the bank as it would not pay to pick it out by hand.

Let us now look for a moment at the cost of extracting a ton of coal; The average width of ground to be worked in order to extract the coal is 6 feet, that is to say there are 2 1/2 feet of coal and 3 1/2 feet of slate between the walls (the slate in some places is very hard) and allowing 2/5 for waste, a man would require to mine 94 cubic feet, this with the help of a laborer is a good day's work. These figures therefore clearly show that every ton of coal costs \$5 to extract and put it in the shute in the mine. Then it has to be drawn from the mine and cleaned, and then run down the upper tramway to the storage shute, then from the storage shute over the lower tramway to the wharf.

I verily believe that were I to go into the minutae of the matter, a ton of coal would cost \$10 before it could be put on board ship.

The Queen Charlotte Coal Mining Coy. “Limited” will declare dividends when the Siwashes here leave off lying and stealing.

It would be a waste of time to comment at large upon the parties who drove the tunnel.
Suffice it to say that, were they miners and honest men, they would have told the company to let the coal remain in the bowels of the earth and their money in their pockets.

## Friday 9th December 1870 {#sec-volume-2-9-dec}

Showery today.

Began the alterations of the shute, but material for this job is scarce and defective.
I feel very tired tonight have been working very hard all day.
I am anxious to get the coal down from the mine before snow sets in.

## Saturday 10th December 1870 {#sec-volume-2-10-dec}

This has been quite a fine day, in fact too mild for December.
I fear we shall pay for this yet.

There was a great rumpus amongst the Indians today.
It arose out of a married man having slept with another woman - not because of the crime he had committed (for with them to do such as that is no crime), but because he had not paid her for having allowed him.
There he sat in a canoe that lay on the beach whilst six women were blackguarding him.
It did not seem to disturb him any; he sat and looked at them and said nothing.
Not so his wife; she and her friends kept it up warm with the others.
I don't know how they settled it, nor yet do I care.

## Sunday 11th December 1870 {#sec-volume-2-11-dec}

Showery until about 5:00 when it cleared up.

Took a walk round the Indian camp in the evening.
Just as I had got into the last hut, a messenger came to tell me that Captain and Lady Skidegate had arrived from Skidegate Town and wanted to see me, so I made my adieu and went to receive my visitors.

The chief object of their call tonight was to get some more medicine for the old woman's leg, which is much better and healed up in several places.
Captain Skidegate is a very cunning fellow, and requires to be watched very closely.

Mrs. Skidegate appears very shy and bashful in the presence of strangers - in fact it is hardly possible to get her to converse at all, but when no third party is present she can talk enough for half a dozen - and an “Artful Dodger” she is, but I know enough of the Indian character not to be caught napping.

The Captain showed me a letter tonight which was addressed to Richard Edwards from H.
Chater, and dated 9th July 1870.
The substance of the letter was that he, Chater, had sent to Edwards by Captain Gold 8 lbs of tobacco and 10 lbs of pork.
I asked him why he had suppressed the letter so long, and how it came into his possession.
He said it was left at Skidegate Town for him and was not delivered to him by Chater.
Mrs. Skidegate said that Chater had frequently told her that he intended giving Skidegate a paper of recommendation before leaving and thinking this letter was such a paper, they did not think it worth showing to me, but they had shown it at Gumshaew (sic) and there learned that it referred to Captain Gold.
I called in Beardsell to see if he could give me any information with regard to the matter.
He told me that Chater was one of the men who had gone down to Victoria last July.
Being short of provisions here, he and other two (sic) engaged Captain Gold to take them to Gumshaew for provisions, and on their return, they learnt at Skidegate that the “Otter” had come for them, so they awaited her return at Skidegate.

Chater had, therefore, sent Captain Gold on, and given him these articles for Edwards which Gold willing had forgot to hand over.
My opinion is that Gold and Skidegate divided the stuff between them, and suppressed the letter.

Skidegate was very anxious to get the letter back from me, but I told him that it did not belong to him and as Edwards had worked here for the company it was my duty to forward it to him.
He did not seem to relish this very much and begged that I would not mention the matter to Captain Gold.
I told him I would not, but what Edwards might do in the matter I could not say.

## Monday 12th December 1870 {#sec-volume-2-12-dec}

Showery all day.

Beauchamp is all right again, and went to work this morning.
Completed my alteration of the shute today.
But the flat screen at the bottom of the incline where the cars are tipped is not required, and as it entails a great amount of shoveling I will board it over and give it as much grade as possible into the shute.

It is quite frosty this evening, and my stove pipe tumbled down whilst I was making a fire, which I had to extinguish.
It is rather cold so I am going to take a walk on the wharf and go to bed.

## Tuesday 13th December 1870 {#sec-volume-2-13-dec}

This has been a delightful day, but rather frosty.

Commenced putting coal into the shute from the mine; got down 10 loads.
A very small day's work.
We are unaccustomed to the working of the road, and it being very dangerous in frosty weather I thought it better to take plenty of time and prevent accidents.
I attended to the starting of the car on the tramway, and put Beardsell at the drum to brake her down the incline.
Beauchamp drove the horses, and a capital driver he is.
He is very careless however, and requires to be watched; should an accident happen to the car on this road both man and horse would be killed.

## Wednesday 14th December 1870 {#sec-volume-2-14-dec}

Very frosty all day.

We very nearly had an accident today.
The Indian who is shoveling the coal into the shute at the bottom of the incline forgot to make the hook fast to the empty car.
The consequence was that when the full car was pushed over the incline she ran off like lightning.
I called to Beardsell to give her all the break as something must be wrong, and ran to the top of the incline to see.
The hook fortunately caught round one of the cross pieces that support the foot plank and prevented the car from running away, as I don't believe the brake would have stopped her without the weight of the empty car, and the chances are that the Indian would have been killed, also two boys who were with him.
In order to prevent an accident of this kind, I had instructed Beauchamp, when he ran the car forward to the top of the incline, to call out all ready and wait for a reply before letting her go, and upon this occasion he received the usual reply of all ready.
I asked the Indian why he had called out all ready without attaching the hook; he said the boys were bothering him at the time.

There ought to be a white man attending to the car, but I am short handed and this Indian has been accustomed to the work.
I have however ordered Beardsell to see that the hook is attached in future.
Took down 10 cars.

## Thursday 15th December 1870 {#sec-volume-2-15-dec}

This has been a beautifully sunny day, freezing pretty hard in the shade.

Beauchamp had his shoulder put out of joint twice today.
I had no difficulty in putting it in again.
When the doctor put it in at Nanaimo, I watched how he did it: I also asked him to give me a hint (in case anything of the kind happened on Queen Charlotte) which he very kindly did, and explained it very fully.
I feel very thankful now that I got these hints from him.
Beauchamp has good pluck; as soon as I had put it in he jumped into the car and drove away.
Took down 12 cars today.

## Friday 16th December 1870 {#sec-volume-2-16-dec}

Change in the weather; light showers all day.

Only took down 8 cars: had to take the horses down to be shod.
I have not felt at all well today, and don't feel any better tonight.
My spirits are very depressed.
As the Indians say, I have got a sick tum tum, and quite homesick.

This is a weary dreary hole.
No change, but one continual groove of coal and Siwashes and Siwashes and coal; and a growling grumbling ill tempered set of men to deal with.
I very often dream of being out of it, and I sincerely wish I was.

## Saturday 17th December 1870 {#sec-volume-2-17-dec}

This has been a dry day, the sun did not shine, but we had no rain.

Took down 16 cars today and I find that amount is quite enough for the horses, poor brutes.
It is either a “feast or a famine” with them; we have plenty of oats but no hay, and not a blade of grass for them to pick up if they are turned out: the consequences that they have no bottom in them.
I believe they were kept alive on flour last February.
They are very willing brutes, but have been very badly used.

## Sunday 18th December 1870 {#sec-volume-2-18-dec}

This has been a beautiful day, freezing very hard.

The sugar is done so we have to drink our tea and coffee straight.
I don't mind it much, but Laiken and Riely grumble fearfully.

We have about 3 weeks more flour, and should no vessel make its appearance very soon I will have to go to Gumshaew for provisions, I don't like the idea of going out to sea in a canoe at this season, but of course we must have grub; I will however put off the evil day as long as I can and the men may growl until they are tired.

The Indians had a grand dance and feast tonight.
It was very beautiful to stand on the wharf and listen to the singing.
They keep such good time that one would imagine they had been trained: the women have charming voices.

## Monday 19th December 1870 {#sec-volume-2-19-dec}

Freezing very hard all day.

Had to keep the rails covered with ashes until the frost got rubbed out of them.

Laiken and one of the Chinamen had quite a rumpus.
Laiken was running coal out of the mine and tipping it into the shed where Ah Hen was cleaning it.
It appears there was a quantity of coal in the shed, and when Laiken tipped the car it struck the heap of coal, causing it to come back and jammed Laiken's finger between the body and frame.
He began to curse and swear at the Chinaman to pull the coal away so as to allow the car to tip and extricate his finger, but Ah Hen did not understand him and took hold of the car and pushed it back, squeezing Laiken's finger.
This made him perfectly furious.
He raved and swore at him like a wild beast, and afterwards threatened to strike him.

The Chinaman does not understand much english, but a more industrious hard working man I never saw.
Poor fellow, he came to me in a great state of excitement and told me how Laiken had been abusing him.
He said Laiken think himself very smart, perhaps he too muchie; me no think me very smart, you like me fight him, me fight him.
I told him he had better not fight, and I would talk to Laiken - which I did, but I did not make much out of him.
He only cursed the place and everybody; he is a thorough bad man.
Took down 16 loads today.

## Tuesday 20th December 1870 {#sec-volume-2-20-dec}

The frost has gone, it has been thawing all day, but no rain.

The road worked beautifully today, got down 17 loads.
Half of my six months is up today, and I shall rejoice when the other three are gone; it makes it very unpleasant for me to have to deal with such men as Laiken and Riely.
I told them one evening that when a boy I was taught to look upon coal miners as being a degraded class, but that prejudice had fled when I came to manhood.
This however was the result of not having come in contact with them.
It is not a matter of wonder that good men become demoralised when they have no other association but coal miners.

## Wednesday 21st December 1870 {#sec-volume-21-dec}

Very foggy all day.

Finished taking down the coal.
85 car loads in all, making about 105 tons.
We have been signally favoured with good weather for this job and I feel very thankful that no accidents have occurred.
The cost of taking down this coal has been \$0.87 per ton, but were the horses in good order and in fine weather, it could be taken down at a cost of \$0.50 per ton; and from the shute to the wharf at \$0.25 per ton.
There ought to be 4 cars in use on the upper tramway, with a turn out so that an empty car would be ready instead of waiting for the empty car coming up the incline.

## Thursday 22nd December 1870 {#sec-volume-2-22-dec}

It has been raining a little all day.

Christmas will soon be here, and a miserable one it will be to me.
The usual dinner and Sunday hot tumblers won't be forthcoming, but that does not trouble me; it is being separated from those I love, and knowing that my dear wife will be lonely without me.
This will be the first Christmas we have not spent together since we have been one, and I trust it will be the last until it please God to separate us.
I often wonder whether couples can be happy who are separated from each other so many months in every year.
It is said that use is second nature, but I don't think I would ever get used to this sort of thing without feeling miserable.

## Friday 23rd December 1870 {#sec-volume-2-23-dec}

This has been a wretched day snowing and sleeting by turns.

We have been exceedingly fortunate in getting the coal down at the time we did.
I fear we are going to have a severe winter; the Indians prognosticate a great deal of snow.
I hope they may be disappointed.
It is bad travelling to the mine now; the mountain we have to climb up is almost knee deep in mud.

## Saturday 24th December 1870 {#sec-volume-2-24-dec}

This has been another miserable day, sleeting throughout the whole day, and the wind bitterly cold.

At noon I told the men as Christmas Day fell on a Sunday they would be cheated out of a holiday, but as this was such a bad day they need not go to work in the afternoon.

Bought a couple of wild geese from the Indians for tomorrow's dinner.

## Sunday 25th December 1870 {#sec-volume-2-25-dec}

Christmas has come at last and a most wretched day it is.
The rain has been pouring down all night, and still continues.

My head aches fearfully this morning and I feel very depressed in spirit; the thought of bygone days and happy hours, make me miserable.

About 1:00 o’clock PM a canoe arrived from Skidegate with the intelligence that a ship was at anchor off Skidegate Village.
I immediately hired a canoe and three Indians and started.
After a pull of two hours we reached the ship, which was the barquentine “Lulu” bound hither for a cargo of coal.
Captain Knowles received me at the gangway and expressed himself very glad that I had come as he could not speak to the Indians and he was desirous of securing one as a pilot to take him into Hastings, which I had no difficulty in obtaining for him.
He introduced me to Mr. Carpenter, his chief mate, whom he said had seen my wife and children when they came on board.
He expressed himself very sorry at not being on board at the time.
He brought out the whiskey bottle and some biscuit and cheese, which was very acceptable as I was very cold and wet.
I remained an hour and 1/2 on board.
He wanted me to wait for tea, but the wind was increasing and a dark night before us so I declined his kind invitation, but begged a bottle of whiskey and a piece of cheese from him for the men.

I dare say Captain Knowles would be thought by some to be a capital fellow, but my opinion of him is that he is a rough low life down east Yankee.
I hope I may think better of him.
One little incident made me look at him with astonishment: shortly after I went on board, who should make her appearance but young Kindawash.
As she entered the cabin, he winked at me and said she had slept with him last night.
I told him the less he had to do with them the better, and if he did not take my advice he might find out to his sorrow when it was too late.
He replied in an offhand sort of way that he always made a practice of such things in every port, and he did not see why he should make this one an exception.

Arrived at Hastings at 8:00 o’clock; we had it very rough.
The men were very pleased with the bottle of whiskey; it was quite a happy surprise for them.

I opened my packet, but fancy my dismay when I found that my wife’s letter was not in it.
I felt like starting back to the ship.
Had it been day instead of night I certainly should, but the Captain thought he would get in tomorrow, so I had to console myself that a day would bring them.
I learned from Mr. Fawcett's letter that my darling had sent me a box of Creature Comforts, so I concluded that the letter would be in it.

Who can tell what a day may bring forth?
This morning I was thinking of home with a heavy heart wondering if my dear ones were well, and now I have spoken to a man who actually saw, and brought a message from, my dear wife only 12 days ago.

## Monday 26th December 1870 {#sec-volume-2-26-dec}

It has not been raining quite so much today as yesterday, but blowing more, and the wind being from the southwest the ship has not got in, and should the wind continue in this quarter she will have to lie where she is.

Had a call from Mrs. Skidegate tonight.
She was in great trouble; it appears from what she told me that after I left the ship yesterday her husband and a number of Indians went on board, also several women.
The Captain handed round the whiskey too freely, making her husband and others drunk; the consequence was that they kicked up a rumpus on board which nearly resulted in a bloody fight, but fortunately some sober ones came off and got the drunk ones away.
The Captain was drunk himself; he made the women drunk and then stripped them naked and treated them in a way not to be recorded.
Mrs. Skidegate implored me to prevent a like occurrence.
I told her I was quite shocked at the whole affair, and I should certainly prevent the Captain from giving the Indians whiskey.

I fear I shall have some trouble with this blackguard captain.
The Indians hitherto have been very peaceable: in fact my orders have been law amongst them, but they have such a thirst for whiskey that they would sell their soul for it.
I regret that I am not in a position to hand the Captain over to a constable.
Yesterday whilst I was on board he gave the men who were in the canoe with me some whiskey.
I cautioned him about it and said it was very unwise to give them any.

## Tuesday 27th December 1870 {#sec-volume-2-27-dec}

Raining and blowing great guns all day.

Dispatched a canoe and three Indians for my box this morning; they did not get back until 8:00 o’clock PM.
The canoe was several times half filled with water, and nearly swamped once.
On Sunday night I was low spirited because I did not get my darlings letter but I feel worse tonight after reading it.
Had I have known that she would have been treated so badly I certainly never should have come here; and these nice things that she has sent me - how do I know but what she may be without such things herself.
I feel more than thankful for them, but my heart is very sad.

I pray that God may will it that my dear wife will fare better than she has done, and be spared in good health to welcome my return with gladness.
The sweet little flower from the dear hallowed spot made me cry but did me good, for I know he is with Jesus.
Amid the heavenly throng, Singing with Saints his praises, Learning the angels’ song.

## Wednesday 28th December 1870 {#sec-volume-28-dec}

This has been a showery day, but fine comparatively speaking to what it has been.

The “Lulu” got to the wharf at 3:00 PM.
She had a fair wind, but nearly went ashore.
The Captain was rather fuddled and in the cabin amongst the Indians instead of being at his duty, but I feel very thankful that she has reached the wharf in safety.
The Captain has invited me to spend the evening with him which I have accepted, and am therefore just going on board.

## Thursday 29th December 1870 {#sec-volume-2-29-dec}

This has been a delightful day; scarcely a cloud to be seen.

We had a fearful night last night.
Shortly after I went on board it began to blow.
Two of the Indian chiefs were on board viz.
Captains Gold and Skaylus, also a number of women.
The women however soon left after I went on board; amongst them was Mrs. Skidegate and her sister.
I spoke to the Captain about giving whiskey to the Indians and showed him he what danger he was exposing us to by giving it to them.
He expressed his regret at having done so, but said it was all gone so he had no more to give.

At 8:00 o’clock an Indian came to the wharf and shouted for me to come on shore, a tree had fallen across one of the Indians huts killing one woman and breaking Mrs. Skidegate’s arm and leg.
Captain Gold came into the cabin to tell me.
I got up and prepared to go on shore when he came rushing in and said the ship had broke loose from the wharf.
I told the Captain what he said.
We ran out on deck.
The Captain shouted let go the anchor and fortunately the chief mate was about to let it go when the order was given, otherwise the ship should certainly have been dashed against the rocks.
It was blowing a perfect hurricane.
The cause of her breaking loose was from the three piles giving way.
These piles were driven for the purpose of making a ship's bow fast to.
They could not have been properly driven; one was hauled right out, the other two pulled underwater.
The hawser of course slipped off and away went the ship.
Captain Gold had his canoe alongside; I got into it, and he pulled me on shore.

I made all speed toward the Indian camp; what a pitiable sight was there, men women and children, huddled together in groups along the beach afraid to enter their huts.
I inquired of them where the sufferers were; they told me in Captain Skaylus’ Hut.
The girl who had been killed I soon saw that it was all over with her; a branch of the tree had driven her head into the fire.
She was a horrible sight.
I examined Mrs. Skidegate’s leg and arm and found that neither of them were broken, but badly bruised.
Her left shoulder was very much so.
My attention was next called to a little girl about seven years old: she had been driven into the fire.
Her little arms ,one leg and the whole of her chest was fearfully burned.
Poor child, my heart bled for her.
She was sitting blowing on her hands to keep them cool.
I hastened to my room, got some Chlorodyne painkiller, Copal Varnish and Linseed oil.
I gave Mrs. Skidegate a dose of Chlorodyne, bathed her shoulder and arm with painkiller, directed her mother to bathe her leg and keep cold water cloths on her left temple and eye (which were also very much bruised).
I then attended to the little girl.
They had put some dirty pieces of rag on the broken places which I found a great difficulty in removing, but she was very patient and thanks to my dear wife who had supplied me with plenty of old linen, I soon dressed her.
Poor child, she seemed so grateful for the relief I had given her.
Mrs. Skidegate was much relieved of pain by this time, and thanked me very warmly.

:::{.callout-tip title="Medical Explanation"} 
See @sec-appendix-4-2-29-dec
:::

Whilst I was attending to these poor wretches, one of the huts caught fire and was burned to ashes.
The Indians did not attempt to put it out; there were some large trees behind it which frightened them.
I also heard a tremendous crash.
I asked one of the Indians to go and see what it was.
He soon returned to say that a large tree had fallen across the bridge and severed it in two, smashing 2 canoes and narrowly missing a hut where a number of Indians were.

When I got back to the store I found 3 girls and an old woman standing at the door: they belonged to the hut adjoining the one which had been broken down, and there being several trees behind it, they were afraid to enter it.
They begged of me to give them shelter for the night, which I did.
I gave them an old sail which they spread on the floor; each took a chunk of wood for a pillow.
They cuddled up and soon forgot their troubles.
Quite a number of women sat behind the store all night.

The track was covered with fallen trees this morning, and the bridge is a great misfortune.
I turned a number of Indians to clear the trees off, and some of the men to repair the bridge.
The ship has been discharging ballast all day, she is moored safely again alongside the Wharf and will discharge freight tomorrow.

## Friday 30th December 1870 {#sec-volume-2-30-dec}

It has been snowing all morning, cleared off about 2:00 o’clock.

Got all the freight ashore and finished repairing the bridge.
Captain Knowles informed me that he would be ready to receive coal tomorrow, but the Indians don't seem to care about working.
They are greatly disappointed at the Company not having sent up goods to pay them.
They have been working for a long time without pay, and have been looking forward to this ship’s coming with great expectations.
It places me in a very awkward position with them as I fully expected a stock of Indian trade goods.
I told them it must have been an oversight, but that I would write and have them sent up by a schooner.

## Saturday 31st December 1870 {#sec-volume-2-31-dec}

It has been snowing all day there is now about 6 inches of snow, this is very unfortunate, just at the time we require good weather we are going to have it very rough.

Could not get the Indians to go to work, so I will have to stop mining and turn all hands to ship loading on Monday.
It has cleared off tonight, and freezing very hard.
The Company having sent me 6 bottles of rum, and this being the last day of the old year, I am going to give the men 3 bottles and go down and see the old year out and the new one in with them.
Little Kate's cake is too good to place before such swine, so I asked Beardsell in to have a glass of brandy and a piece of cake.
I told him I had only one fault to find with it, it was too rich; he enjoyed it very much.

Thou signpost of time, that has almost passed away, 
Where are the thousands that rejoiced at thy birth?
Many have been called to the realms of day, 
And shall no more mingle with this world's mirth.

## Sunday 1st January 1871 {#sec-volume-2-1-jan}

The New Year has begun with rain, it has been pouring down all day.

Went to bed at 2:00 o’clock this morning; the men got very jolly over the rum, in fact Laiken went to bed drunk at 11:00 o’clock.
The others were a little more temperate.
I gave them other \[sic\] two bottles today.
They seemed as though a little drop would do them good and when they know it is all gone they will bother me no more.
We had the plum pudding at dinner today and delicious it was; the mince pies were excellent so I made a good dinner and thanked God that he had spared me in good health to see the beginning of another year, and prayed that my darlings at home might be thankful for the same preservation.

I have felt very lonely today; home with its comforts is sadly missed.
I wish I could say Happy New Year to someone whose feelings would be reciprocal.

The Captain has had a great many Indian visitors today, but I did not go on board.
I am thoroughly disgusted with him.

## Monday 2nd January 1871 {#sec-volume-2-2-jan}

It has been raining all day.

Began to load the ship this morning.
The men worked well notwithstanding the rain.
At night they were just as though they had been drawn through water.
I was almost chilled to death standing by the weighbridge, weighing the cars, but having been exposed so much to the weather lately I think I stand the cold better than I used to do.
Rain is bad enough, but I would much rather have it than snow, as the latter will prevent our working the tramway.

## Tuesday 3rd January 1871 {#sec-volume-2-3-jan}

This has been a miserable day, it has been sleeting and blowing from morning till night.

The shute for loading the ship is a great annoyance; it is hung on a hinge, and when the ship is up at high water it is perfectly flat, requiring two men shovelling to keep it clear.
The company promised to make a new shute in Victoria and send it up by the ship, but they have sent me lumber instead for me to make it here.
The lumber however is not strong enough for the purpose.
I proposed to the Captain that we should work when the tide suited, that is to work five hours during the day and five at night, which he is agreeable to, so we will begin tomorrow.

The Captain's cabin is nothing better than a House of ill fame, it is shocking to see the way he is going on.

## Wednesday 4th January 1871 {#sec-volume-2-4-jan}

This has been another wretched day, sleet and snow at intervals throughout the entire day.

We have had a serious accident today; it pains me to record it.
Fearing that we would soon have a fall of snow which would prevent our getting the coal down from the mine, I sent a party this morning to take it down.
I instructed Beauchamp to exercise great care as the tramway would be very bad.
When they got up they found a good deal of snow on the track, which had to be cleared before they began.
They succeeded in getting down two loads, but it appears the friction of the car running over the rails made them as slippery as glass.
When they pushed the third car over, it took a run.
Beauchamp jumped onto the brake and tried to stop her, but soon found that he had no command over her - but he thought she would run down all right and stop at the drum.
But alas!-
in going round one of the curves she swung to one side and ran off the track breaking Beauchamp's leg and thigh, also his arm above the wrist and dislocated his shoulder, one or two flesh wounds and the back of his neck so badly bruised that he could not move his head.

This accident happened about 2:00 o’clock PM.
Beardsell dispatched an Indian immediately to tell me.
When I saw the Indian coming running, my heart stood still for some seconds.
I knew something serious had happened.
As soon as I learned what was wrong I made all speed for the upper tramway, calling to the men to follow me.
I soon reached the spot and found Beauchamp in great agony.
I dispatched some of the men for a small bedstead and mattress to carry him down on.
I remained with him until the other men came up, when I left to prepare splints and bandages.

When I got down I went on board the “Lulu” and asked the Captain if he knew anything about setting legs, but he did not.
I got a surgical book from him, which was a great assistance to me.
The materials prescribed by it for such cases I had none, but got the next best.
I tore up one of my sheets for bandages, and a piece of one of my blankets for wadding for the splints.
I set the leg and arm, but the thigh was so much swollen that I could not find out where it was broken.
I put a wet bandage round it and concluded to wait until tomorrow.
The muscles of the shoulder were so bruised and swollen that I could not do anything with it; besides, I had no chance to get a good pull at it, from his arm being broke.
I bathed the bruised parts well with painkiller, but he is still in great agony.

:::{.callout-tip title="Medical Explanation"} 
See @sec-appendix-4-2-4-jan
:::

## Thursday 5th January 1871 {#sec-volume-2-5-jan}

It has been sleeting all day.

I am very tired tonight, having remained up with Beauchamp all last night, and I will have to remain up with him tonight again.
He is very low and weak; none of the men seemed to care about sitting up with him.
Laiken however has volunteered to sit up until 12:00 o’clock so that will give me a little rest.
With the assistance of one of the sailors (who has seen fractures reduced) I set the thigh; it is broke near the hip.

I spent a terrible night of it: I had not at any one time ten minutes relaxation throughout the whole night.
I used three bottles of pain killer on his neck and shoulder.
He was continually calling to me to try and alleviate his pain, and the only way I could do this was by the continued application of pain killer.
I trust that God will bring him safe out of my hands.
He is very impatient and irritable, but I can make every allowance for this.

## Friday 6th January 1871 {#sec-volume-2-6-jan}

This has been the worst day we have had yet; it has been snowing nearly all day.

Beauchamp is very weak today; he only slept about one hour last night.
The men think he will die, but I don't.
His eye is good, and the inflammation is going down from his leg.
He has to be fed like a child he is so weak.
I have Beardsell waiting on him during the day as I have to be on the wharf weighing the coal.
I don't feel so tired tonight as I did last night, but have got a slight cold.
I suppose being up all night and so much exposure during the day is the cause of it.

I am going to remain up with Beauchamp tonight again, but I must make some other arrangements tomorrow as I cannot stand it much longer.

## Saturday 7th January 1871 {#sec-volume-2-7-jan}

This day has been quite a treat, clear and frosty.

Put on board all the coal we had on the wharf: 355 tons.
On Monday we will try and get down to the shute what there is at the mine so as to have it all in the shute before we begin running it over the lower tramway, but I fear we will have great difficulty in working the upper road.
Beauchamp's accident has rather frightened the men.

Beauchamp is much better today.
I succeeded in getting his shoulder in, which has made him feel much more comfortable.
His requirements are not so many now.
I have placed one of the Chinamen to wait on him day and night.

I had to quarrel with Captain Knowles today.
He has been giving more whiskey to the Indians.
The confines of the habitation of the Evil One must have disgorged him as a good riddance.
The scenes that daily occur on board are not fit to be recorded; he appears to be lost to all sense of shame.

## Sunday 8th January 1871 {#sec-volume-2-8-jan}

It was sleeting all morning and snowing all afternoon.
It has cleared up tonight, and freezing hard.

I don't feel well today.
The three nights sitting up was rather too much for me.
No one can tell how much I would enjoy my “Ain Fireside” today.
I always feel depressed in spirit on Sabbath days: I suppose it is because I have more time to think of home and my dear ones.
All day I have been repeating over and over

Jerusalem my happy home, 
Land ever dear to me.
When shall my labours have an end 
Then I thy joys shall see.

What would I not give to be singing that hymn at home with my dear wife tonight.

Beauchamp is progressing very favorably.
He very foolishly pulled one of the splints from his thigh last night.
I got quite angry with him about.
\[sic\] He said no one would give him anything to scratch his leg with, so he pulled it out for that purpose.
He is a very frivolous, foolish man for his years.
On some points he has no more sense than a child.
He is continually having his leg moved.
I try to reason with him, but to no purpose.
Should anything go wrong with his leg now, I have the conviction that I have done my duty by him.

:::{.callout-tip title="Medical Explanation"} 
See @sec-appendix-4-2-8-jan
:::

## Monday 9th January 1871 {#sec-volume-2-9-jan}

It has been freezing very hard today.

Went up to the upper tramway this morning and cleared the snow off it which was 18 inches deep; this occupied nearly the whole day.
Laiken and myself repaired the broken car, put the horses to it and hauled it up to the mine.
We did not more than two thirds fill it for a trial.
I would not allow the horse to be put before it until we saw how it was going to work.
Made a long rope fast to it and told the men to hold her back, and see if we could lower her down gently.
I locked the two back wheels with sprags, and started her; we kept command over her for about 50 yards, when she gradually gained speed until the men were compelled to let her go.
I jumped clear of her just before she came to the first curve.
Beardsell was the last man to let go; he was thrown with great violence against some stones which bruised his side very badly.
She ran for a distance of about 300 yards, when she was thrown off the track at precisely the same place where the other one was upset.
The men positively refused to have anything more to do with it.

I am quite downhearted at the failure as I will not be able to give the ship a cargo without this coal, but our lives are of more value than the coal, so it will have to remain where it is until we get better weather.

## Tuesday 10th January 1871 {#sec-volume-2-10-jan}

Freezing very hard all morning; snowing this afternoon.

We have been clearing the snow from the lower tramway, but this afternoon has undone all our work.
I am at my wits end to know what to do.
We are doing our best and yet we are only killing time.
The company have been very much to blame in sending a ship at this season of the year.
It is truly disheartening; everything seems to be going against me.

## Wednesday 11th January 1871 {#sec-volume-2-11-jan}

This day has been the same as yesterday, freezing hard in the morning and snowing all afternoon.

Told the men to knock off clearing the track and started in to make a sled.
I have no great hopes that it will work well, but we may manage with it.
It is very cold: the thermometer is standing at 18°.

## Thursday 12th January 1871 {#sec-volume-2-12-jan}

It has been snowing all day.

There is now four feet of snow on the track, nearly two feet fell last night.
Tried the sled: the horses took it up very well, but when loaded they could not start it from the shute.
We tried them for nearly two hours, but it was no use - they could not start it.
I proposed that we should make a snow plow wide enough to extend across both rails.
We soon made it and it works charmingly.
It is very heavy work for the horses but I think we will master the snow now.
It throws up the snow each side like two walls.
There is considerable shoveling to be done behind it.
I have engaged the ship's crew to assist us tomorrow so I think by their help we will have the road in working order by Saturday.

Aley’s Comforter is a great comfort to me just now and a little bit of Kate's cake at night, with a wee drop of brandy goes very nice.
I wish someone was with me to enjoy it too.

## Friday 13th January 1871 {#sec-volume-2-13-jan}

Very frosty all day; the wind has changed, and the weather looks settled for a while.

We have been plowing and shoveling snow all day; the track is cleared at last so we will begin tomorrow to take coal down.
There was five feet of snow on the coal in the shute.
This we shoveled on one side until the half of the coal is run out, then it will have to be shoveled back.

We are out of coffee now and the tea won't last more than three days.
It is bad enough to be compelled to sweeten one’s tea with syrup, but much worse to have none to sweeten.
The men growl a great deal about it, but I fear they will growl a great deal more, when the tea is gone.

## Saturday 14th January 1871 {#sec-volume-2-14-jan}

It has been cold enough today to chill one to the very marrow, the wind cuts right through one.

We have been taking coal down, but it is very slow work.
The rails are like glass, making it exceedingly dangerous, We spag both the back wheels, and notwithstanding this she comes down the first incline like lightning.
We then put the horse to, and drag her down with the wheels locked.
The brakes are entirely useless in such weather.
Only got down six cars; enough to make one swear.
The ship’s lay days will be up on the 17th; then she will be be on demurrage at \$40 per day.
I wish Trounce and Gibbs were here now to work this beautiful road.

Trounce has deceived the company beyond all expression.
They would be quite justified in bringing a suit against him for damages.
To pass such work as he has done was abusing the confidence reposed in him and swindling the company.

Robinson has been no better than Trounce.
He piled up a lot of slate and dirt and received pay for it as coal; the company have been fearfully robbed.

## Sunday 15th January 1871 {#sec-volume-2-15-jan}

A little snow fell last night clear and frosty all morning, snowing a little this afternoon.

Had it not snowed last night the men would have worked today to save demurrage if possible, but they did not like clearing the track.

The Captain invited me on board to dinner today.
After dinner he came on shore and spent the evening with me.
I was heartily glad when he left; his whole conversation was nothing but filthy rubbish and obscene language.
He is the most demoralised man I ever met.
His language shames the very Indians.
His crew has styled his cabin the ‘Mad House’.
There is not an Indian woman in the whole camp that he has not slept with, but they appear to be getting either afraid or disgusted as they seldom go on board now.

Harmless little Scotchguy came to me yesterday complaining that the Captain had been abusing his wife and daughter.
Although I sympathized with him, I told him he had himself to blame by allowing his wife to go on board.
I tried to explain the nature of such a sin, and told him how white men felt upon such matters.
He said he was a Siwash and did not understand such things, but he was sure Captain Knowles was not a ”@sec-appendix-tihee” or he would not have acted in the way in which he had done.

This has been an ill spent Sabbath and I ought to have kept out of the company of that blackguard Captain, but as it was the first time he had asked me to dine with him I could not very well refuse, and he invited himself to my room in the evening.

## Monday 16th January 1871 {#sec-volume-2-16-jan}

Freezing very hard all day.
Thermometer down to 15° and very windy.

Got down 10 carloads today; the men had to leave off several times and warmed themselves.
The coal is frozen so hard in the shute that I have to keep two men in it with picks.
My cold is rather worse.
I suppose I won't get rid of it until the ship leaves.
I will then be able to lay up for a few days.

## Tuesday 17th January 1871 {#sec-volume-2-17-jan}

The frost still continues, it has been colder today than yesterday.

Got down eleven loads today.
Beardsell is complaining of his side where he got it hurt on the upper tramway.
He says he will try and hold out until the coal is down.
He is the only man I have who has the pluck to run the car over the upper incline.
I rode down on one today with him, and what with the velocity of the car and intense cold I was perfectly benumbed.

Laiken and Riely make a great song as to what they could do, but if it was left to them the coal would have to remain in the shute.

## Wednesday 18th January 1871 {#sec-volume-2-18-jan}

Very frosty today; thermometer down to 12°.

Got down 10 loads today; there are only two more remaining in the shute.
I told the Captain today that owing to the bad weather it would be impossible for me to give him a full cargo.
He got in a fearful passion and wanted me to keep his vessel on demurrage.
I told him it would pay him very well, but it would not pay the Company.
The only thing I regretted that he would get pay for 500 tons of coal, and I could not give him that amount.

I had quite a quarrel with him this forenoon.
Yesterday I was on board to see how the coal looked in the ships hold.
He called me into the cabin and asked me to explain something \[not fit to be recorded here\] to an Indian woman who was sitting in his cabin.
I did so very reluctantly.
It appears the Indians had been talking over the matter in their camp at night, and came to the conclusion that something must be wrong with \[sic\], the consequence was that three of them went on board this morning for an explanation.
He sent for me and accused me of having told the woman yesterday something different from what he said, and told me if I did not take back what I had said, I would be sorry for it.
I denied the charge of course and told him I had nothing to take back, and left the ship.
During the afternoon he went round the Indian camp and exposed his person in every hut, before men women and children.
Some of the Indians ran away, thinking he had gone mad.
He tried to turn the Indians against me, but they only laughed at him.
The Indians hold a great many papers from me, kind of promissory notes for labour, for which they will receive pay when the goods come up.
He took a number of papers representing these, showed them to the Indians, and then put them in the fire, telling them that my notes were of no more value than these, and that they would never get paid for their labour.

I regret very much that it is not within my power to hand him over to the authorities for punishment.
Had he behaved himself properly amongst the Indians they might have believed his statements, but they only laughed at him and told him he was scatty (mad).

Our tea is all done.
The cook is burning barley and nicknamed it coffee; it is a very fair substitute.

## Thursday 19th January 1871 {#sec-volume-2-19-jan}

The weather has changed.
It was snowing nearly all last night, and snowing and raining today.

Had to clear the track to take down the two loads.
Went to the upper tramway with a party to see if we could do anything with it, but there being five feet of snow on it I abandoned the idea of clearing it.
It would take four days at least to do it, and should it freeze much we would not be able to work it.
Went on board and told the Captain that I could give him no more coal, and gave him his discharge telling him that his papers would be ready in the morning.
I will be up all night writing to the company so I must drop this.

## Friday 20th January 1871 {#sec-volume-2-20-jan}

It has been very raw and cold today, showers of sleet throughout the whole day.

Went on board this morning with my letters and papers; the Captain refused to sign the Bills of Laiding because I would not write on the back of his Charter Party that he should be paid freight for 600 tons.
I read his Charter Party over to him and explained the nature of it, but he either did not understand it or he thought of playing a Yankee trick on me.
Each party was bound in the penal sum of \$3000 for non fulfillment of contract: I told him this was all he could claim, besides I had no power to interfere with the contract.

He used some most abusive language, and declined to carry my letters.
Also that he would go to sea without signing the Bill of Laiding.
I went on shore.
He pushed his vessel from the wharf and anchored her in the bay, ready for sailing whenever a breeze would spring up.
I have been trying to get my letters on board to put in the hands of one of the crew to deliver it to Pickett and Harrison of San Francisco, but did not succeed.
I have an idea that he won't go to sea without my giving him his proper discharge; he surely knows enough not to commit himself in this way.
But I verily believe there is no crime too great for him if he thought he could commit it with safety to himself.
I cannot find words strong enough to depict his true character.

It appears he made a confident of Riely: “birds of a feather flock together”.
Riely is a great blackguard, and worthy of his confidence.
Riely told me something that the Captain had said to him in confidence which made me very sorrowful.
He must be worse than the very devil himself.
Before recording what he did say, I will first relate the circumstances which brought about.

On the day that poor Beauchamp was so low and feverish, I went on board and asked him as a great favor if he would kindly permit me to look over his medicine chest and permit me to take there from a small quantity of such medicines as I thought would be useful for Beauchamp: he readily assented. The only medicines I took were a few James’ Powders for fever, about an ounce of Laudanum in case of violent inflammation, and about 2 ounces of Camfor liniment to rub his shoulder with.
I wanted a little sweet Spirit of Nitre (he is slightly troubled with gravel) but there was only a few drops left in the bottle so I did not get any.
I showed the Captain what I had taken and thanked him most heartily for his kindness.

:::{.callout-tip title="Medical Explanation"} 
See @sec-appendix-4-2-20-jan
:::

Now what the Captain told Riley was that I had been on board and searched all through his medicine chest and took there from medicines for syphilitic afflictions.
Fortunately the men were all in the house when I came from the ship and saw the medicines I had brought.
They also saw me administer one of James's Powders to Beauchamp at once.
Riley, blackguard as he is, knowing this to be a lie told me what the Captain had said.
I could not feel angry with him, but felt very sorry that such a monster should be going about in human shape.

Beardsell’s side is very bad.
I fear it will lay him up for some time.

## Saturday 21st January 1871 {#sec-volume-2-21-jan}

It has been raining all day.

At 8:00 o’clock this morning the Captain sent the second mate on shore with a note requesting me to come on board with my papers.
I went on board immediately, but found him in no better mood than he was yesterday.
He again wanted me to interfere with his Charter Party, which of course I flatly refused.
He stamped and raved and cursed like a madman.
I jumped up, took my hat and told him if he could not conduct himself in a proper manner I would go on shore.
He then quietened down a little and asked me to sit down again.
I did so, at the same time telling him that, unless he would listen to reason and be a little more temperate in his language, I could have no further dealings with him.
He listened to what I had to say.
I then wrote his discharge, which he accepted.
I received a protest from him which is not worth two straws, but it satisfied him, and was a matter of indifference to me.
He then signed the Bills of Laiding and received my packet.
I wished him a safe voyage and took my leave.

He got up anchor at 2:00 o’clock, but there was not sufficient wind to carry him out of the bay so he had to drop anchor about 4:00 o’clock, only making about a mile.

## Sunday 22nd January 1871 {#sec-volume-2-22-jan}

Showery all day.

The ship got away this afternoon.
I feel to breathe freer now that she is out of sight.
What between the bad weather and Captain I have been worried out of my senses.
On the evening when we came down from the upper tramway after a fruitless attempt to takedown the coal, my beard and hair was white with frost.
Beardsell remarked to me that I would be that colour by the time I got to Victoria.
I suppose he saw how much it worried me.
I will, however, give up fretting about it.
I have the satisfaction of knowing that I did my duty to the best of my ability.
It was surely against my wish that the ship had to leave with 65 tons short of a cargo.
Four months of my time was up yesterday.
I thank God for having preserved me in good health, and pray that He may grant that I return safe to my dear ones at home.

I have not had much time lately to be much with Beauchamp, further then asking him every day how he was and asking the Chinaman if he was attending to my instructions by keeping the leg wet with cold water.
The answers I got from both were very satisfactory.
Last week I engaged an Indian to attend on him, the Chinaman and he having quarreled.
Today I thought I would see what the leg looked like.
The silly fool had actually pulled all the splints from the thigh; some he had burned, and some he had hid under his bed that I should not see them.
The bandages he had left on, also the bandage securing the long splint which runs from the hip to the heel.
I asked him what on earth had tempted him to do such a thing; he said his thigh itched so that he could not bear them on.
I unbandaged the long splint, took off the other bandages.
The fracture had knitted and appeared strong, but fearfully crooked.
I showed him what he had done, and told him that he would have himself to blame for having a short crooked leg.
He could not see, however, how he was to blame, but wanted to put the blame on the sailor who suggested the long splint, and was very intemperate in his language.
He is an old fool and not a grain of gratitude in him.
I made some new splints and rebandaged it, but I feel confident that it won't come straight.

## Monday 23rd January 1871 {#sec-volume-2-23-jan}

It has been very foggy and cold today.

Began mining again today.
There is only one keg of blasting powder left, which will soon go; then we will have to cease mining.
I don't know what the company could have been thinking about, not to send me some.
I fear Branch must have done the same when he got to Victoria as he did with me; kept his mouth shut on the stealing affair, leading them to conclude that I must have made a mistake by ordering powder.

Beardsell’s side is very bad today, I am afraid he has ruptured himself.
Laiken and Riely, the uncharitable dogs, insinuate that something more is wrong with him than he cares to speak about.

## Tuesday 24th January 1871 {#sec-volume-2-124-jan}

This day in point of weather has been very similar to yesterday.

My cold is much worse.
On Saturday night I took a blue pill, and on Sunday morning a black draught.

:::{.callout-tip title="Medical Explanation"} 
See @sec-appendix-4-2-24-jan
:::

I ought not to have gone up to the mine yesterday.
Traveling through the wet snow made my feet quite wet, and standing in the mine afterwards must have given me a fresh cold.
I shall take a holiday until I get over it.
This is not the sort of place for a man to be sick, there are few comforts.
I feel the want of a cup of tea very much, but say nothing: Laiken and Riely growl enough for the lot of us.

Laiken has a nasty insinuating way with him, he is not man enough to speak out, but throws out all sorts of dirty hints.

## Wednesday 25th January 1871 {#sec-volume-2-125-jan}

The rain has been pouring down in torrents today.

Have been sitting in the house all day reading, and eating “hyou” bread and jam, but it is very dreary work.
It is bad enough to be going about in this weary place, but much worse when compelled to remain indoors.

## Thursday 26th January 1871 {#sec-volume-2-26-jan}

It has been raining again today but not so much as yesterday.

Beardsell’s side is much better today.
He has been bathing it well with hot water, and remaining very quiet; the least exertion gives him great pain.
We are sadly in want of a good medicine chest and book.
It is highly essential that there should be such a thing here, and should the company carry on these mines it won't be my fault if such necessary appendages are not sent up.

## Friday 27th January 1871 {#sec-volume-2-27-jan}

The weather has been mild today compared to what it has been; had it not been for occasional showers of rain, it would have been very pleasant.

The Indians had a great feast and dance to night, and although invited I did not attend.
My cold is somewhat better so I intend to take care of myself for the present.

## Saturday 28th January 1871 {#sec-volume-2-28-jan}

This has been a dry day, but dull and cheerless.

Went up to the mine today.
It is very bad travelling on the upper tramway.
The late rains has \[sic\] made the snow very heavy.
One sinks over the knee at every step, and it is quite a drag to pull your leg out again.
Several large boulders and roots have rolled down the hill and blocked up the track in places.
This is a considerable expense in itself, keeping the track clear from the incessant slides.

## Sunday 29th January 1871 {#sec-volume-2-29-jan}

How still!
the morning of the hallowed day.

All nature seemed hushed in repose this morning; It was beautiful and clear and not a breath of wind: began to rain about 10:00 o’clock, has been quite showery all day.

A canoe arrived from Skidegate today.
The Indians said the ship only crossed the bar yesterday: adverse winds compelled her to lie off Skidegate for a week.
I trust she will have a speedy voyage.
This ship has been a great disappointment to the Indians, Captain Gold especially.
They fully expected that she would bring a great many “Iktas” to be given to them as a ‘Cultas Potlatch’.
Our friend Trounce has been the cause of this; he told old Gold that his father was going to send a ship here for coal - a four master!!!
, that she would be loaded with goods to be given away and he (Gold) would get the lion's share.
Poor silly credulous old Gold has been terribly gulled.
I tried to console him by telling him that the ship that had come did not belong to Trounce’s father, but when Trounce’s father's ship with the four masts!!!
did come he would then have a benefit.
He did not say much, but I fancy he thinks Trounce’s big ship is a myth.
I don't think he looks upon Trounce now as being such a great Nabob as he had represented himself to be.
In fact, the majority of the Indians speak of him with contempt.

I have frequently questioned these Indians to see if they have any idea of a Supreme Being.
They all say they believe in a higher power than mortal man, but they are very far from the true knowledge.
They have a terrible dread of smallpox; when that epidemic comes amongst them, they believe that God has sent it as a judgment upon them for their past sins, but they don't look upon evildoing as a sin; the sin to them is in being found out.

## Monday 30th January 1871 {#sec-volume-2-31-jan}

The weather today has been similar to yesterday.
Showery.

Beardsell has gone to work today.
The week’s rest has done him much good, but he is not quite well yet.
Beauchamp is going on all right; his appetite is good, the cook makes him some chicken soup every day.
If Fell was within hearing just now, he would not hear a very good account of himself.
When I ordered the preserved chicken from him I told him I wanted it in case of sickness and to let me have the best, but he must have sent me some old stock; one half of the tins are bad.

## Tuesday 31st January 1871

It was very frosty this morning, and continued so all day, it is thawing tonight however and looks like rain.

Had a call from Captain and Mrs. Skidegate this evening.
They brought me some more bad news of Captain Knowles.
It appears he had a large quantity of Indian whisky on board.
He offered it for sale whilst he was lying off Skidegate, but found no purchasers.
He would not take anything but cash; the Indians had no money but offered him skins which he would not accept.

This shows how much he heeded what I had said to him about giving them whiskey.
I suppose he thought he would be clear of the place, and it was a matter of indifference to him what became of us.

## Wednesday 1st Februry 1871 {#sec-volume-2-1-feb}

The rain has been coming down in bucketfuls all day; it beats anything I ever witnessed.

About 3:00 o’clock this afternoon the ditches on the lower tramway became blocked up from the washing away of the banks and pieces of timber.
The water came running down the track like a river.
The men being up at the mine I got an Indian; he and I worked for nearly two hours before we got the ditches clear.
It was very fortunate that I remained at home today.
Had I been at the mine when it occurred, 300 yards of the tramway would have been washed away.
The mountain torrents rise very rapidly; three hours steady rain will transform them from a dribble to a cataract.

## Thursday 2nd February 1871 {#sec-volume-2-2-feb}

Although it has been raining all day, it has been fair when compared with yesterday.

The facing I built against the new piece of road was washed away by yesterday's rain, but the road being on solid ground stands firm.
The coal near the air shaft in the mine has become very soft; in fact it is perfectly worthless, but we have to work it in order to extract the other.
The seam is decreasing in thickness very rapidly, and full of faults, making it very dangerous to work.

## Friday 3rd February 1871 {#sec-volume-2-3-feb}

Raining and sleeting all day.

I am heartily tired of this miserable hole, I long to be out of it.
What between the bad weather and continued growling of Laiken and Riely, it is enough to make one go mad.
I have told them 50 times that I sincerely regret that the tea, coffee and sugar has run out, but that growling and cursing and swearing from the time they open their eyes in the morning until they close them at night won't better their condition.
But when I talk to them in this way they only curse the more.
I suppose they see it annoys me and I verily believe they keep it up for that purpose, but it is a long road that has no turning and I shall bless the day when I can part company with them.

## Saturday 4th February 1871 {#sec-volume-2-4-feb}

The weather has changed, it has been freezing very hard today, and looks as though we are going to have a continuance of it.

After writing the state of the weather I am often puzzled for something to record.
There is so much sameness in this place that I may say there are absolutely no incidents, or of such a trifling nature, that they are not worthy of notice.
Were I a poet I might enlarge upon the beauties of nature, but not being a poet I am entirely at the mercy of what the day may bring forth.
A man harassed as I am by these terrible men, his mind is not apt to be turned into the channel of the beautiful even if he had a poetical taste.

## Sunday 5th February 1871 {#sec-volume-2-5-feb}

The frost continues, it has been much colder today than yesterday.

This has been a charming day for a ramble among the hills, but there is too much snow, so I have been compelled to remain indoors, or walk on the wharf.

The Indians are high busy preparing for a hunting expedition to Gold Harbour.
Some Indians arrived from there the other day with the intelligence that a great number of seals had been seen sporting in a bay near there.
It appears the weather has been very rough outside, driving them into the quiet waters.
This is also about the time they go fishing halibut.
The waters at Gold Harbour teem with this fish; They cut it up in thin slices and dry it.
This, salmon and potatoes constitute their chief food.
They don't dry so many clams as the flat heads, but eat them fresh in their season.

## Monday 6th February 1871 {#sec-volume-2-6-feb}

The weather still continues very frosty.

The mine will soon be at a standstill unless I can trade some powder from the Indians, which is very doubtful.
They must have plenty judging from the number of kegs they stole, but of course they all deny having stole it, and to trade it would be to compromise themselves.
It will be very awkward to have the mine stopped as it will not be an easy month to keep the men employed without exposing them to the weather every day.

## Tuesday 7th February 1871 {#sec-volume-2-7-feb}

Freezing very hard still.

The Indians appear to be very fond of this sort of weather; numbers of them turn out to chop wood and work at their canoes, perfectly naked.
I asked them why they did so in such cold weather.
They said it makes them strong and hardy.
They have another peculiar way of making themselves (as they say) proof against cold; they get half a bucket of sea water, dissolve snow in it until it is nearly full, they then gorge themselves with this water and bring it up again like a stream from a firce (sic) pump.
They repeat this again and again until all the heat is drawn from the body.
Then they rush to the fire, shivering like so many young pups.
This must be very injurious to them, but they think it is “@sec-appendix-hyassclosh”

## Wednesday 8th February 1871 {#sec-volume-2-8-feb}

Frost continues and increasing in intensity.

I have not been very well today, I can hardly describe what it is, the matter, except that my head has been aching, but there is something more than a mere headache.
I feel dull and listless.
A cup of good tea upon such occasions as these would be worth its weight in gold.

“Alas!
I am as a preacher who loveth his own sin.
Confidentially and by the way of confession, I own to a tenderness, amounting almost to the illicit, for this seductive extract.
I suspect it was popular in the garden of Eden before the Fall.”

## Thursday 9th February 1871 {#sec-volume-2-9-feb}

Today in point of weather has been just such a day as yesterday.

Quite a number of Indians are making canoes.
This weather seems to suit well for that purpose.
They are hewing away from morning till night.
The manner in which they make these canoes is as follows.
After they have chosen a tree (cedar) which is very indifferent here, they hew a hole in it close to the butt.
Into this hole they place a quantity of pitch wood, then set fire to it.
They allow it to burn until the heart of the tree is consumed.
It is then hewn down, and from this shell the canoe is made into rough shape.
It is then taken to the camp and placed on the beach.
When in this state it is usually about two inches thick.
They hew it down to a proper thickness with a small adze.
It is then half filled with water, a large fire built on each side of it and a great number of stones made hot, which when properly heated, are thrown into the water in the canoe.
It is then covered over with mats and allowed to steam for half an hour or so.
During this time the outside of the canoe is kept wet by dashing water over it.
The mats are then removed and the stretchers put inside to bring it to the width they want.
The stones and water are then removed.
The canoe is allowed to remain in this way for a day; these temporary stretchers are removed and permanent ones put in.
The canoe is now complete, and ready for service.

## Friday 10th February 1871 {#sec-volume-2-10-feb}

The frost today has been too severe to suit my constitution.
I have not a thermometer, but I should say there is at least 20° of frost.

Ceased mining operations today from want of powder, the slate is so hard that the miners cannot do anything with it with the pick.
Several of the Indians have promised to send me some fine powder, which I hope they will do.
I don't like the idea of being next to idle for the next six weeks, which will be the case unless I can carry on the mine.
If we can't make anything for the company, I don't want them to lose by us.

## Saturday 11th February 1871 {#sec-volume-2-11-feb}

It has been freezing again today,

Oh my!
terrible to think of at night, when I get into bed I pile on coats, pants or anything I can get a hold of, but it is a poor substitute for someone you can cuddle close up to.

This sort of weather may suit a Russian very well, who can eat tallow in the same way in which I would eat bread, but my poor weak stomach declines to receive such fuel to keep up the animal heat.
Have been repairing the broken car on the upper tramway as I intend to have another try to take down the coal.

## Sunday 12th February 1871 {#sec-volume-2-12-feb}

> “Hail!
> Sabbath, thee I hail!
> The poor man's day.
> On other days the man of toil is doomed to eat his joyless bread lonely.
> But on this day the frugal meal he shares.
> He shares with those he loves.”

How often have I repeated those lines since I have been here!
How often have I wished I could have shared one of these Sabbath dinners with those I love?
The “Day of Rest” to my mind is a very beautiful poem, but the poet did not take into consideration a man in my position.
Assuredly I do not eat my meals alone, but with those I cannot say I hate, but I certainly do not love.
Those lines therefore were not intended for me under the present circumstances.

The weather has changed it has been thawing all day.

Some Indians arrived from Gold Harbour last night with a supply of halibut; this is a most delicious fish.
When we can get it, we have it for breakfast, dinner and supper.
Salt beef is at a discount when halibut comes into the market.
The crabs here are very fine; they are a different kind from those got in the waters near Victoria.
Oysters, there are none: those delicious pearly little creatures that we eat alive are dead to us here.
Clams are in abundance, but they savour too much of the Siwash to suit my taste.

## Monday 13th February 1871 {#sec-volume-2-13-feb}

This has been a beautiful day, just freezing enough to make it pleasant.

Had all hands cutting firewood; Have traded enough powder at present to make a start mining again, which we will do tomorrow.

Had a call from Captain Skidegate and Lady.
He has engaged to get me 10 lbs blasting powder at Skidegate, for which I have agreed to pay £20 in return.
He says he has none himself but some of the other Indians have.
This I don't believe.
Of course it is quite natural that he should try and impress me with the idea that he had no hand in the theft; but it won't do Captain, you are a cunning dog, but you will find me a match for you one of these days.

## Tuesday 14th February 1871 {#sec-volume-2-14-feb}

This has been a showery day.

Began mining operations again this morning.

Late last night a canoe arrived from Gumshaew with some Indians who had come up from Victoria by McKay's schooner.
I am greatly disappointed at not receiving any letters, but I suppose my dear wife did not know of her leaving, otherwise she would have written.
The Indians brought several bottles of whiskey with them; two bottles were given to Captain Gold.
He sat down and did not attempt to move until he had finished them.
He has been going about led by two Indians, yelling and roaring like a wild beast.
He became sober down a little by 3:00 o’clock and came
