# Volume IV {.unnumbered #sec-volume4}

## Tuesday 18th April 1871 (continued) {#sec-volume-4-18-apr}

Left Hastings at 1:00 o’clock PM in a small canoe; arrived at Skidegate at 5:00 PM very wet. Engaged a large canoe and three Indians to go with us. Wet all night slept very badly.

## Wednesday 19th April 1871 {#sec-volume-4-19-apr}

Got up at 6:00 o’clock.  Showery. 

Indians don't want to start until noon. Left at 11:00 o’clock AM with a good breeze in our favour. Reached Capt. Skidance [sic] hunting camp about 4:00 o’clock PM. Set in very stormy. Wet all morning. Went out bear hunting, but did not see any. One of the Indians brought in three grouse. We are about 50 miles from Hastings.

## Thursday 20th April 1871 {#sec-volume-4-20-apr}

Although I had made a good bed with dried grass I slept very indifferently.

The wind howled at a fearful rate all night. Got up about 6:00 o’clock, went down to the river about 200 yards distant and had a good wash. By the time I got back one of the Indians had plucked the grouse. I stewed one for breakfast with potatoes. I have not relished a breakfast like this for months past.
The sea very rough and wind increasing. 

Went out after breakfast and shot two grouse. One of the Indians brought home a goose, so if we have to remain here some time we won't starve. The wind has been howling all afternoon. We had a shower of rain, but it did not last more than an hour. Got 2 more grouse and 2 ducks this afternoon. We cooked the grouse for dinner (stewed) and drank the soup instead of tea. Prepared 2 grouse ready for breakfast tomorrow morning, as we hoped to make an early start. 

The country here is very flat. It is excellent farming land; the stream of water is full of trout. How I longed for a my [sic] fishing tackle. Went to bed about 9:00 o’clock. 

7 months from home today. 

## Friday 21st April 1871 {#sec-volume-4-21-apr}

Got up at daybreak. Very cold, clear and frosty with the wind blowing from the West which is in our favor. 

Went down to the stream and had a wash, warmed up the stewed grouse and took breakfast just as the sun was rising. The soup is an excellent substitute for coffee. 

We had considerable difficulty in getting our canoe launched. The beach is very flat here, and the tide being low we had to carry her 150 yards then launch her amidst the breakers. We all got our feet and legs wet, which was not very comfortable.

The wind kept up until about 11:00 o’clock, when it died away and we had to pull. We had several showers, one of which was hail and bitterly cold. Reached the last point before we come to the bar at the N.E. corner of the island at 5:00 o’clock PM making about 25 miles today. We had hoped to make the bar, but the wind got up and shifted to N.W. which was dead against us. Consequently we had to put ashore and camp for the night. Our bread is exhausted so we supped tonight on salt beef and potatoes, after which we stewed a goose to be ready for breakfast. 

This is a beautiful night, the wind is falling. Made up our beds on the beach. The Indians went out and dug up some shellfish. They resemble clams in shape, but are of a most delicate flavour. The shell is quite smooth and of an oval shape, very thin. Turned in at rest 9:00 o’clock, with a canoe for our canopy. 

## Saturday 22nd April 1871 {#sec-volume-4-22-apr}

Slept very cold last night; my blankets were perfectly white with frost. 

Got up about 5.30 o'clock, had a good wash and took breakfast and made a start about 7:00 o’clock. Dead calm. 

We pulled to the end of the spit by 11:00 o’clock when a light breeze sprung up and we set sail Descriptn [sic] of spit. to lunch off salt beef straight, not very nice. 

Blew very cold all afternoon. So cold, the [sic] we lay and shook in the canoe, large Rock [Coal] 

Reached Masset at 5:30 o'clock. We were very warmly received by Mr. Offalt the HB Cop. officer in charge here. He invited us up to his house and gave us such a supper as we have not had for months. He is as fine an old man as I have met for a long time. He offered us sleeping room but seeing that it would put him about 
           McKay lost [sic] 
considerable, we accepted sleeping room from the Indian chief here: Wee ha. He is a fine specimen of an Indian and bears[?] and excellent character. Read[?] his papers. Went to bed about 11:00 o’clock, he did all that he could to make us comfortable.

## Sunday 23rd April 1871 {#sec-volume-4-23-apr}

Did not sleep much last night. I was warm enough, but the boards seemed as hard as rocks. 

Got up about 5:30 had a good wash. Mr. Offalt out came down at 6:00 o’clock and said breakfast would be ready in half an hour. And an excellent breakfast it was: bacon and eggs, such a treat! Oh no! I didn't eat any in fact I felt ashamed and apologized to the old gentleman, but really the treat was so great that I felt I must go in a burster. 

The wind was blowing so high this morning that the Indians said it would be impossible for us to go round the bar, and if we ran to try make a portage we could not launch the canoe on the other side for the breakers. Consequently we had reluctantly to make up our minds to remain here for the day. Mr. Offalt was only too glad to keep us. 

Took a walk around a [illegible. Illegible illegible] went round the Indian camp. Every hut has a stick, great deal of carving! 

Took dinner at 3:00 o’clock, stewed [illegible] cakes made with new milk what a treat! We have landed among clover. I could rec[illegible]t here for a month, but time forbids. The Indians who came with us went to see their friends and are now all ready for a start should the wind prove favourable in the morning, which I sincerely hope it may. Sunday here is anything except that day, but the old man is lavish in his kindness, and 
          Description of place
we have everything we can wish for as far as making us comfortable is concerned. Weeha turned out his men[?] to sing.

## Monday 24rd April 1871 {#sec-volume-4-24-apr}

Got up at 5:00 o’clock. Fair wind blowing, but very light. 

Had breakfast at 7:00 o’clock. 

I don't know how to [sic] grateful I feel towards the old man for his kindness. Got what provisions he could spare us and got underway about 11:00 o’clock. Wind blowing from the north. Had to pull [illegible] put ashore about 8 miles on Masset side of the spit about 3:00 o’clock. 

Rain set in. Fried some salt pork for supper, and boiled some to eat on the way. Rigged up a tent to sleep under.

## Tuesday 25th April 1871 {#sec-volume-4-25-apr}

Woke up at daylight. Rain had ceased, and quite frosty. 

Got the Indians up, but they said the wind would not suit to round the spit and the breakers would be too great to land and make a portage, so here we having to remain. This is miserable work. Persuaded the Indians at 10:00 o’clock to run across to the spit to make a portage. They agreed upon condition that I and Beardsell should walk 8 miles, which we did. landed Safely Raining all afternoon. Run the canoe over, but camped in the bush, this is very chafing kind of work.

## Wednesday 26th April 1871 {#sec-volume-4-26-apr}

Slept well last night and warm. 

Woke up at daybreak, but found the wind in the S.E. still, which is dead against us. In fact the breakers are running so high that it is impossible to launch the canoe. After breakfast went out with the rifle and shot four grouse. Cooked 3 for dinner stewed, the soup are excellent. Cooked the remainder for supper and ready for breakfast. 

Raining nearly all afternoon and wind increasing. Went to bed at 8:00 o’clock.

## Thursday 27th April 1871 {#sec-volume-4-27-apr}

Woke up at daybreak. Slept well. Raining; a little wind still in the same quarter blowing quite a gale. 

[Illegible] breakfast of [illegible illegible] for tea. Noon, wind still high. Raining all morning, betraying symptoms of clearing off [illegible]. The biscuit we took with us from Massett [sic] is now exhausted. Made some bread from flour and water and baked it in the ashes. Showery all afternoon. The bread was very good. Wind keeps steady from the same quarter. Went to bed about 8:00 o’clock. Raining.

## Friday 28th April 1871 {#sec-volume-4-28-apr}

Wind not quite so high this morning, but too strong for us. Rain this morning. 

Throat very sore. At noon the wind chopped suddenly round, to the west. Made a hasty meal and got under weigh [sic]. By the time we got started the wind had died away, went round again to S.E. Pulled about 8 miles. Went ashore near the place where we camped the week before. Wind increasing. Made some more dough ready for bread, but could not bake it. 

## Saturday 29th April 1871 {#sec-volume-4-29-apr}

Last night was a fearful night. The wind raved as though it would bring the trees and mountains over us and the rain poured down in torrents. I never witnessed such a night. 
Slept warm. Dreamed
Anniversary
bread in the morning. Indians made a house from brush.
Wind kept up all day. Made more bread in the evening, got everything ready for a start in the morning.

## Sunday 30th April 1871 {#sec-volume-4-30-apr}

Got up at daybreak. Not a breath of wind. Beautiful and clear.

Got the men up and cooked breakfast and got a way a little after 5:00  o’clock. Had not gone far when it began to blow from the S.E. again. A considerable sea got up and being too heavily laden for good trim, we shipped considerable water.  We had to put in at the mouth of a creek, making about 10 miles this morning.
Eargh
Afternoon: wind has been increasing all day. It is now a howling hurricane and betraying strong symptoms of rain. We have taken up our quarters on the beach behind a fallen tree, it being too dangerous to camp in the timber. Made some more bread. Went to bed about 8:00 o’clock. It is a fearful night.

## Monday 1st May 1871 {#sec-volume-4-1-may}

Of all the rough nights I ever experienced, last night beat them. The wind and sea roared like thunder. 

How thankful I felt that we had put in here. Had we have gone on as I once thought of doing, we certainly should have perished. Not blowing quite so strong this morning, but a hurricane still. We are now reduced to bread and molasses. My throat is very sore. How I long to be home. 

Went to bed about 8:00 o’clock. Not very well. I feel worried about being so long away.

## Tuesday 2nd May 1871 {#sec-volume-4-2-may}

Slept very little last night. 

Got the men up at daybreak. No wind. Breakfast in canoe. Came on to blow a little after an hours start; had to row. Reached Skidaws camp at noon, went on shore made some coffee, and got under weigh [sic] again. Showers of sleet and hail. Arrived at Skidegate Town about 8:00 o’clock. Had to row all the way. 

We made about 45 miles today, and were perfectly exhausted from being so long in the canoe and only eating a little bread baked in the ashes, burning a little of the same to make coffee. We felt quite a perceptible change in the weather; it is so much milder at Massett [sic].

The Indians treated us very kindly, boiling us some potatoes for supper, which went very well. Canoe trips are not what they are said to be.

## Wednesday 3rd May 1871 {#sec-volume-4-3-may}

Got up this morning about 6:00 o’clock, but felt little refreshed sleeping on hard boards: not the kind of bed to refresh one. 

The Indians gave us some herrings which we boiled with potatoes for breakfast, and although we had no salt they were very acceptable. 

Left Skidegate get about 10:00 o’clock  for Hastings with a fair breeze. Just two weeks and about the same time since we left here for Massett, and truly thankful [illegible] that we have got through all safe. The Indians throughout displayed great attention and kindness; the Chief at Massett particularly so; he was extremely kind and was very anxious for us to remain. 

Arrived at Hastings at 2:00 o’clock PM.

# End of diary

Note in Time Book: 
Monday 8th May 
Left Queen Charlotte tonight at 6.00 o’clock P.M. 
