# Volume III {.unnumbered #sec-volume3}

::: {.callout-note title="Maps"}
For a map of canoe journey camp sites and routes discussed in Volumes III and IV see @sec-maps-canoe
:::

## Tuesday 14th February 1871 (continued) {#sec-volume-3-14-feb}

to me, I tried to get rid of him, but no use. He told me all his grievances, which he had told me 20 times before, and all his expectations, which he had recited 50 times before.

He said who was God? Where was the man who was God! He alone was the “@sec-appendix-suckally-tihee”; he possessed more land, more water, and had more men under his command than any other man. He was, therefore, God. Now had the dirty Captain been where I could have safely given him a good cudgeling for this blasphemy, I certainly should have done so. I merely told him he was only a dirty Siwash and left him in disgust.

## Wednesday 15th February 1871 {#sec-volume-3-15-feb}

It has been raining and sleeting all day. Most disagreeable weather.

Captain Skidegate arrived today bringing me 10 pounds of powder. It is precisely the same as that we have been using, and without a doubt a portion of that stolen from the Company. This will be good evidence against them, as he will be bound to show where he got it. I gave him a paper of acknowledgement for the amount, received with a promise to pay him. This of course I was compelled to do. The Company may take what steps they think proper in the matter. Powder is only one of the many things they have stolen; there is scarcely a tool left to work with.

## Thursday 16th February 1871 {#sec-volume-3-16-feb}

It has been showery today. Tonight, the rain is pouring down and blowing a hurricane.

Took the splints and bandages off Beauchamp's leg today. The thigh appears strong, but very crooked. This he has himself to blame for, as I have already stated. The break between the knee and ankle has not knitted properly. There is a dark purple streak running along the edge of the shin bone, and opposite the break on the inside of the leg looks as though there were matter. I am not surgeon enough to account for this, nor yet do I know very well how to treat it. I replaced the splints and bandages, however, but did not place them exactly in the same position as they were before. I am sadly disappointed; I fully expected to find the leg all right. It is now six weeks since the accident happened, and although Beauchamp himself has not treated the leg well, I nevertheless expected a better result.
He is very much downhearted about it. His knee is very weak and is still considerably swollen.

## Friday 17th February 1871 {#sec-volume-3-17-feb}

It has been raining and sleeting at intervals all day.

There is now a great quantity of snow at the mine. When it rains and sleets down here, it snows at the mine. It is hard work traveling up the mountain now: I try and avoid travelling it more than once a day. From all I can learn, this is an exceptional winter; they don't usually have so much snow, but rain every day.

## Saturday 18th February 1871 {#sec-volume-3-18-feb}

It has been sleeting all morning and snowing all afternoon.

Truly this is a terrible climate. This island ought to be towed 10° degrees toward the south. I can't imagine how Mr. King managed to exist three years in this place, and without a road to travel on.

The Indians seem to thrive very well, they are all fat and enjoy good health. The majority of the old people's eyes are very weak: this I attribute to the smoke in the hut and their filthy habits. They seldom wash their faces, and are continually besmearing them with pitch and charcoal. They do this (as they say) to preserve the skin; this sort of paint would not suit the delicate fashionable lady.

## Sunday 19th February 1871 {#sec-volume-3-19-feb}

This has been a miserable cheerless day of sleet.

I don't know of anything more calculated to demoralise a man than the non-observance of the Sabbath Day. I know that some will argue that even in a place of this sort this day can be kept as it should be. My experience tells me differently. Habit is everything with a man, and when he cannot keep up that habit by going to the House of God on the Sabbath day, something else will naturally engage his mind, and although I have not allowed myself to do on this day just what I would do on week days, yet I feel that the Sabbaths here are not like Sabbaths. The men, it is true, are not at work; consequently they don't require my presence amongst them, but then I can hear them going about cursing and swearing, and at meals the same old grumbling, so that I may say I have really no change. Should the day be fine (which is very seldom) I can go rambling in the woods and get out of it, but on such days as these my situation is really a miserable one.

## Monday 20th February 1871 {#sec-volume-3-20-feb}

It has been snowing all day; the snow on the upper tramway is now very deep.

It is a fearful job getting out timbers for the mine; This is another oversight. There ought to have been sufficient timber got out in the summer to last the winter, but I think it must have been a standing rule here to let every man fend for himself. There does not appear to have been any forethought about anything.

## Tuesday 21st February 1871 {#sec-volume-3-21-feb}

This has been a beautiful day, clear and frosty, but very cold.

The Chinamen don't like this weather (too muchee cold no good). Poor wretches they don't know much, but are very willing. The other men in my absence impose on them a good deal. The cook is a scamp; he runs too muchee after the Indian women, and I fear he is giving the provisions away, but the Indians are so cunning that it is impossible to find out from them, and he has every opportunity whilst I am at the mine. These women are truly a curse to the place.


## Wednesday 22nd February 1871 {#sec-volume-3-22-feb}

It has been frosty all day, but snowing tonight, and looks as though we were going to have a heavy fall.

A portion of the mine caved today. The slips and faults increase as we go up, requiring a great amount of timbering to keep it secure, but it is better to expand a little labour in this way than to have an accident. The coal is getting much softer and less in width. I don't believe that more than 200 tons could be extracted with safety. This mine has been a great “bilk”; it will not yield more than a fifth of the estimated amount.

Poor Hounslow was right when he said “it was madness to build a tramway to get a little bit of coal that would not pay one quarter of the cost of building the road”, but it has not even done this as the coal will not pay the cost of extraction: therefore both road and mine have been money thrown away.

## Thursday 23rd February 1871 {#sec-volume-3-23-feb}

It has been snowing and sleeting all day. 

There are now at least 10 feet of snow on the mountain. Should it continue snowing much longer the road will become impassable, as it is it quite knocks the wind out of one. The pigs, poor brutes, fare very badly just now. I have nothing to give them to eat. The only way they keep life in is by scavenging on the beach at low water; this is cruelty to animals.

## Friday 24th February 1871 {#sec-volume-3-24-feb}

The weather today has been a repetition of yesterday.

This is very trying weather. Some of the men's boots are so badly broken that their feet is [sic]  wet from morning till night. My own boots hold out pretty well, and by rubbing them with beeswax and oil every night, I managed to keep my feet dry.

## Saturday 25th February 1871 {#sec-volume-3-25-feb}

It has been raining heavens hard all day. 

The snow is so deep that the rain simply becomes absorbed in it, making it very heavy and bad for travelling. I had some happy dreams last night, but morning told me they were all a bubble.
I am longing for the end of March. I usually feel sad at leaving a place, but I shall leave this with joy.

## Sunday 26th February 1871 {#sec-volume-3-26-feb}

It has been raining and sleeting at intervals all day, and snowing tonight.

I am too much down among the dead men to write tonight. I have been maneuvering in all sorts of ways to make the day pass lightly but without success. I can't even settle my mind to read. I see the gray hairs are beginning to show themselves, telling me very plainly that it won't do to worry so much.

## Monday 27th February 1871 {#sec-volume-3-27-feb}

This has been a day of snow. Rain began at 6:00 o’clock PM and looks as though it will rain all night. 

Our powder is nearly exhausted so we will soon have to close mining operations. This is much to be deplored as I shall be at my wits and to keep the men employed. Gibbs was exceedingly fortunate. the Indians tell men [sic] they had only one fall of snow, and so light that it did not last a week. Had last winter been like this, he could not have completed his contract until midsummer.


## Tuesday 28th February 1871 {#sec-volume-3-28-feb}

Snowing still and likely to continue.

We have now worked the mine to within 30 feet of the surface at the air shaft. The coal is very soft here, in fact worthless, and unsafe to work it any higher. In reality the mine may be looked upon as exhausted. 150 tons or so might yet be got, but then it would not pay cost of extraction.

## Wednesday 1st March 1871 {#sec-volume-3-1-mar}

Snowing still. 

We are out of firewood so I had all hands at work today getting some out. Laiken and Riely made a great noise about it. They like a good fire, but growl at having to get fuel. I admit it is not very pleasant weather for wood chopping, but that makes no difference. If the weather was fine they growl all the same.

## Thursday 2nd March 1871 {#sec-volume-3-2-mar}

Slight change in the weather; instead of snow we have had a day of sleet.

Suspended mining operations from want of powder. There are about 80 tons of coal at the mine which I will try and get down to the shute should the weather permit. 

Unbandaged Beauchamp's leg today. The bone appears to be knitted all right now, but there is a very ugly sore on the inside of the leg. I don't know how to account for this, but I think if I can heal it up the leg will soon become strong: the knee is very weak still and very much swollen.

## Friday 3rd March 1871 {#sec-volume-3-3-mar}

 It has been snowing very heavily all day.

I have had the men employed wood chopping, but they don't do much. Hen, one of the Chinamen, got his finger badly hurt. It appears he was holding the wedge whilst the other Chinaman was driving it into the log with the mall. He missed the wedge and struck his finger, breaking the bone, and splitting the flesh from below the knuckle to the point on both sides. It must have been very painful, but he was very patient while I dressed it.

## Saturday 4th March 1871 {#sec-volume-3-4-mar}

This has been a wretched day, snowing, sleeting and raining without ceasing, and blowing cold enough to take one's nose off. 

I did not turn the men out today; they can do a little in dry snow, but when it sleets and rains between, it is not fit to be outside.

This want of powder will be a serious loss to the company. I feel now that we are not earning our grub. It makes me quite low spirited. I know the directors expected great things at my hands, but everything has gone against me - and bad men to deal with, to boot.

## Sunday 5th March 1871 {#sec-volume-3-5-mar}

The rain has been pouring down all day.

A dry Sabbath day would be quite a luxury, but I fear that treat will not come for some time. It is dreadful work to sit moping in the house all day. No change during the week, and the usual way of being compelled to remain in every Sabbath is truly dreadful.

Time is on the wing, a little more patience and, God willing, I will soon be back to “somebody” and that somebody cares for me. So away! Despondency, why should I cherish thee when joy is so near.

>“Watchman, tell us of the night,\
>What its signs of promise are.\
>Traveller, let thy dark be light,\
>Joy and love are not afar.”

## Monday 6th March 1871 {#sec-volume-3-6-mar}

Today has been quite a treat, warm and sunny without a single shower.

The men have been cutting wood all day. Laiken and Riely growl terribly about this kind of work. I suppose since I can't find them work in the mine they expect to be allowed to sit in the house and look at their fingers - as Laiken used to do when he was up here before, but he has someone to look after him this time and he don't like it, and I don't like it. I wish he had someone else than me. I certainly should not covet his position.
The other men go to their work and retire without a murmur.

## Tuesday 7th March 1871 {#sec-volume-3-7-mar}

 Fine until 10:00 when it began to snow, and still continues.

The men only worked half a day, cutting wood.

Had a call from Captain Gumshaew tonight; his son and daughter accompanied him. He is a fine specimen of an Indian: his height is about 5 feet 7 inches; age I should say 35 years, well built, with strongly marked features. He said he had come expressly to call on me. Some of his tribe had been living here for a short time; they had spoken of me in such high terms that he must come and see me. I thanked him very kindly and told him that I felt highly honoured that a chief like him should come forty miles with no other object than to see me and wish me well.
I had a long conversation with him. He told me there was coal at Gumshaew, but the outcrops were not more than an inch in thickness.
After I had exhausted all my questions, he asked me to present him with a testimonial - which I did. Of course I knew nothing of his character; consequently I wrote him one which suited the Indian character in general. Then he wanted me to give him something as a cultaz potlatch: I gave him a few fishhooks, with which he was highly pleased.
His son is about 15 years old, the daughter 19 years. They both resemble him very much; the daughter is rather good looking.

## Wednesday 8th March 1871 {#sec-volume-3-8-mar}

It has been snowing and hailing all day.

The men did next to nothing, cutting a little wood occasionally between the showers.
A canoe arrived this morning from Gold Harbor bringing quite a number of seal skins and halibut. They report very rough weather outside.

## Thursday 9th March 1871 {#sec-volume-3-9-mar}

We had about two hours sunshine today; Snowing and sleeting the remainder.

The men did not work. I have no means of keeping them employed, which is a serious loss, but the Company are accustomed to this sort of thing. It appears, from what I hear, that the men never did make more than half time.


## Friday 10th March 1871 {#sec-volume-3-10-mar}

It rained all morning and cleared off about 12 o'clock. It has been quite fine ever since.

Took the men up to the upper tramway, and commenced clearing the snow off; it is four feet deep, very heavy and wet. It must have been six feet before the rain fell.

It is quite warm tonight, which I think portends a change of weather for the better.


## Saturday 11th March 1871 {#sec-volume-3-11-mar}

This has been a charming day. Were it not for the great amount of snow lying, one might say summer had come.

The men made good progress clearing today, there is a wall of snow on each side of the track eight feet high. It is a beautiful sight to stand and gaze along the track between these walls; the sun shining on them makes them have the appearance of crystals.
We are now out of syrup. The only warm fluids we have to drink now is barley water “straight”; not very pleasant. 

Should the weather keep fine until Monday and appear settled I will go to Gumshaew and try and procure some tea, sugar and coffee.

## Sunday 12th March 1871 {#sec-volume-3-12-mar}

This has been a most gloriously beautiful day.

I have been sorely depressed in spirits all day. Had some very unpleasant dreams last night. Before going to sleep, I was thinking of my poor boy: whenever I would shut my eyes he was always present with me. I saw him as I used to see him in good health, merry and happy. This kept me awake some time. I dreamed that I had returned home and found my dear wife very sick. She was sitting up and in a chair: when I spoke to her she seemed too much worn out and exhausted to reply to me. I did not see any of the children and, strange to say, I did not inquire after them. This is the only time I have dreamed of home without seeing the children, and the second time that my poor boy was not sitting on his mother's knee. Afterwards I dreamt that lice was crawling over me. How to account for this horrible dream, I cannot think. I trust in God that my dear ones at home are not sick, and are not going to be. The thought of such a thing makes me feel quite unhappy and miserable. 

Engaged a canoe and four Indians to take me to Gumshaew tomorrow should the weather be fine.

## Monday 13th March 1871 {#sec-volume-3-13-mar}

Started at 7:00 AM this morning with four Indians for Gumshaew. The sun was shining in all his glory and delightfully warm for this time of year.

The mountains with their snow clad peaks look very beautiful. There are six peaks in a range with Mount Seymour. The third one is much higher than Mount Seymour and shaped like a sugar loaf. There is a tradition among the Indians that this peak is an old squaw who departed this life long ago; the others are departed men. As we were approaching Skidegate the Indians pointed out a high mountain to the eastward which were they said was behind Gumshaew. There is a tradition amongst them that the island was level at one time and this was the only mountain to be seen, but I think it very doubtful.

We reached the bar at the entrance to Skidegate Harbour at 12:15 o'clock PM. Landed on the point and two of the Indians walked across to see how the wind was. They soon returned and reported wind against us with a heavy sea. The old man to whom the canoe belonged said we would have to camp here for the night unless the wind changed. I did not much like the idea of this, but of course I had to submit.
During the afternoon I took my rifle and walked some distance into the bush. I came upon a small lake where there were numerous wild geese and ducks. I shot two of the former and carried to camp. When I got back the Indians had made a fire, which was very acceptable. The wind had increased to a hurricane and very cold. I gathered some dried rushes of which I made a bed under a tree, took supper of cold beef and bread, had a smoke and walked along the beach until about 7:00 o’clock.

I have frequently heard miners say that they preferred camping out to sleeping in a house. This may be so, but I assure you I did not much like the idea of it, more especially since my only companions were Indians. Shortly after we had laid down for the night it began to rain. I had covered my head over with the blankets and soon went to sleep.

## Tuesday 14th March 1871 {#sec-volume-3-14-mar}

I have already had a surfeit of camping out. The rain poured down heavens hard all night, this making my blankets were perfectly saturated with water. I cannot say that I was very cold during the night: the rain falling on my head woke me up about every hour when I would pull the blankets over it and go to sleep again.

I got the Indians to turn out about 5:00 o’clock this morning and told them to turn the canoe bottoms up so that we might sit under it. This was done in very short time, and here we sat until 10:00 o’clock when it ceased to rain, but still blowing and a heavy sea running. Having sat so long under the canoe, I was chilled to my very heart, and cold meat and bread for breakfast did not warm me much. 

Since we could not proceed on our voyage, I proposed that we should run back to Skidegate Village and there await a favorable chance as I did not much like the idea of camping out, and our blankets all wet. Accordingly we started for Skidegate which is about 6 miles from where we had camped. When we got about half way across the wind changed, favorable for Gumshaew. Consequently we headed the canoe for the bar, which I found out when too late was very foolish. The breakers running in over the bar were something fearful, and worst of all the Indians became so frightened that I was afraid they would not keep command of our frail bark. The bar where we crossed it is about half a mile wide, but we had a stiff breeze with us which enabled us to ride the breakers like wild duck. The only danger in crossing the bar in such weather as this is the danger of these breakers striking our broadside: in that case nothing could save us. But the old Indian who was steering knew his duty well, meeting every one bow on. There was one very large one; it came rolling on us like a mountain of boiling water increasing in height as it neared us. I could see the Indians sitting holding their breath to await the result: another moment and our little bark was half filled with water, but rode over it beautifully. The force with which the canoe fell as the breaker passed under her sprung a leak in her near the bows. As quick as lightning, one of the Indians had his knife out and soon stopped it with cedar bark fibre which he had at hand. Another set to work bailing and before the next one met us we were comparatively snug. The Indians seemed as thankful as I was when we got clear of it. 

We now headed for Gumshaew, but the wind slackened and a heavy sea running, we made very little progress, only reaching Skidegate Copper Mine at 4:30 o'clock PM.

There is an old Indian hut here where we took up our quarters for the night. The Indians gathered some wood and soon made a rousing fire. We hung our blankets up to dry which by the way took some time. I was very tired having paddled for six hours and half. I was very glad when my blankets were dry, which was about 10:00 o’clock.

## Wednesday 15th March 1871 {#sec-volume-3-15-mar}

Called the Indians up this morning by peep of day; I had slept well and felt very much refreshed. Went down to the river which ran close by the hut and had a good douche with its cold crystal wave. By this time the Indians had made up their blankets and were about ready for a start. I soon ate my breakfast, which consisted of bread and a drink of cold water from the river; not very cheering in a cold frosty morning.

When we left Hastings the weather was so fine that we expected to make the round trip in two days; this accounts for my running short of grub.

We got underway at 5:00 o’clock. It was a beautiful clear morning but very cold. I smoked two pipes before I could get any heat in me, but when the sun came out, and the exertion of paddling, I soon got warm. We reached Gumshaew at 12:00 o’clock PM, having had to paddle all the way.

Mr. Hardgreaves, who is in charge of Captain McKay's store, was very glad to see me, but could not spare me any of the articles I wanted. He had only a week's supply on hand for himself. This was too bad after having come forty miles for a little tea and sugar, and to go back without any made me feel quite dispirited.
He kindly invited me to remain all night, which I declined as I was anxious to get back, and there was a little breeze springing up in our favor. I invited myself to take some dinner with him as I was rather hungry, but when he intimated that I would have to wait until he had boiled some pork I begged of him to make me a cup of tea as I could not wait for the pork. I don't remember to have ever enjoyed anything so much as this cup of tea. I was quite a new man after it. He pressed me very hard to try some dried salmon and Indian grease, but the smell of the grease was too much. I ate a little of the salmon, and was satisfied. He eats this stuff as though it was honey. He appears very much demoralised, dirty, ragged and slovenly and very thin. He has not got even the time of day. I question very much if he knew the day of the week. It is truly wonderful how soon a man falls. He has only been six months stationed here and has already fallen into the habits of the Indian. He may wash his face occasionally, but I doubt if he ever combs his hair. God grant that I may never fall so low as that.

Started homeward at 2:00 o’clock PM, the wind blowing pretty fresh in our favour. About 4:00 o’clock  the wind almost died away and it began to rain. On starting, our first idea was to make the copper mine and camp for the night, but we had such a good breeze that I ordered the Indians to keep out to sea and run for Skidegate.

We reached the bar at 9:00 o’clock. It was very dark. There was not much of a sea, so we crossed it very comfortably. After we got inside, the wind entirely died away. There was nothing for us now but to paddle against a head tide, and being all very tired, wet and hungry, it was very laborious work. The old man who sat behind was completely used up. I tried to encourage them by paddling well myself, but it had no effect. I suppose they thought that when I was paddling the canoe was going along and the [sic] might take it easy. 

Owing to the heavy tide rips, the Indians said it would be unsafe to cross for Skidegate Village, so we stood for Captain George’s house at the entrance to Gold Harbor, which is about four miles below Skidegate. This we reached at 1:00 o’clock  AM. It had rained without interruption since 4:00 o’clock; nine hours, so you may easily guess our condition. 11 hours sitting in a cramped position, and nine out of that under a pouring rain. When I got out of the canoe my legs were so stiff and cold, they refused to carry me. I staggered about like a drunk man.

One of the Indians went up to the hut and roused up the inmates. They got a lot of pitchwood, and in less than 10 minutes we had a roaring fire. I sat down by it, but could scarcely feel the heat of it. My teeth clattered and my legs shook until I thought they would never become still.
Captain George’s wife came and sat down by me, lit her pipe and handed it to me. She kept feeding in pieces of pitchwood opposite to where I sat and tried to make me as comfortable as she could.
The piece of bread that I had remaining was so wet that it was unfit to eat. She saw this, and immediately put some potatoes on to boil. I made quite a meal of them  - yes even without salt. The worst of the whole was I had to stand by the fire and allow my clothes to dry on me. I knew this was very bad, but there were so many Indians in the Hut that I felt ashamed to strip.

Mrs. George spread a couple of mats in front of the fire on which I spread my blankets and laid down about 3:00 o’clock, weary enough.

## Thursday 16th March 1871 {#sec-volume-3-16-mar}

Got up at 7:00 o’clock this morning, and felt more tired than when I laid down. I did not sleep much. I never got properly warm and got up shivering. Mrs. George boiled some more potatoes for breakfast, and although I made my breakfast of them, they did not go down well. I was rather out of sorts. 

It was blowing a perfect hurricane this morning and against us. The Indians said it was useless to attempt to pull against it, so there was no help but to wait until it moderated. When we landed this morning I understood there were only one hut here, but after I got up I found there were two. In the other one there were a family who used to live at Hastings; it appears they had removed to this place. They have only one daughter, a fine girl about 16 years old. For cleanliness she is quite an exception among the Indians. Her name is “Kitquini”. She did some sewing for me several times whilst she was living at Hastings. Soon after I had got up and was sitting by the fire warming myself, I was surprised to see her peeping through the cracks of the boards. I beckoned to her to come in. I soon learned from whence she came. Had I known that she was living so near I certainly should have asked her to share her bed with me instead of standing by the fire drying myself. I went along to the Hut where she was living and laid down, but could not sleep. The Indians were drinking sea water mixed with snow and vomiting it up again. This made me quite sick, so I walked about outside until the wind moderated, which was about 1:00 o’clock PM. We got underway, but having a strong wind to paddle against amid frequent showers of snow and hail, we reached Hastings at 5:30 o'clock. I was as hungry as a hawk, and made a hearty dinner. Bad as my home is here, it is superior to anything I saw during my trip, and glad I was to get back.

There is no certainty of the weather here at this season; it may be warm and sunny in the morning and snowing in the afternoon.

## Friday 17th March 1871 {#sec-volume-3-17-mar}

This has been a beautiful day, a little frosty in the morning but the sun soon dispersed it.

During my absence the men according to my instructions had cleared the upper tramway and had worked two half days taking down coal. They have been taking down coal all day. Everything is working smoothly and I sincerely hope we will not have any accidents.

The Indians who went with me to Gumshaew are quite used up. Poor old Skaylus has caught a violent cold and is confined to bed; I gave him some medicine and told him to keep warm, but this I know he won't do.

## Saturday 18th March 1871 {#sec-volume-3-18-mar}

This has been another delightful day.

We took 23 loads of coal over the tramway today; should it be fine on Monday we will finish it.
The men, as I anticipated, are sorely disappointed at my not getting some tea and sugar. Laiken and Riely have been tearing and swearing all day, something terrible to listen to. How I long for the day to come that I may part company with them. May God guard me from falling into the evil habits of these men. I often wonder that they are not struck senseless on the spot for their blasphemy. Laiken is the worst of the two; he cannot his open his mouth without swearing.

## Sunday 19th March 1871 {#sec-volume-3-19-mar}

It has been showery today, but very mild.

I don't feel any the better for my trip. I am anything but well and my bones are all aching. This is a miserable place for one to be sick, not the slightest comfort of any kind. I feel as though I should like to be petted a little when I am in this state.

One of the Indian chiefs called upon me today and asked me to write a letter to the missionary at Nass. Four of his men were going to visit that place with the object of trading with the Nass Indians. It appears these Indians here and those at Nass have not been on friendly terms, but the Indians here are anxious to heal up old sores and open a friendly traffic with their neighbors. The chief desired this to be made known to the Nass Indians through the medium of the missionary. I wrote him a letter expressing his sentiments. They are going to start tomorrow, weather permitting.


## Monday 20th March 1871 {#sec-volume-3-20-mar}

This has been a delightful day, quite a treat.

Finished taking down the coal and I am happy to add without the slightest accident, but every precaution was taken to prevent one. 84 carloads which I think will produce 80 tons or thereabouts. We have now done all we can do except clearing the lower tramway. In case anything should come in and want coal, this I will get the men to do, although I find they don't care about working and under the circumstances I cannot push them. The Company have [sic] broken their contract by allowing us to run out of tea and sugar which places me in a very awkward position with the men. When I told them that I wanted the lower tramway cleared they did not refuse, but cursed and swore a great deal.

Today completes our six months. A weary time it has been, but I thank God for having preserved me in such good health, also the men under my charge. It has been bad enough with poor Beauchamp, but it might have been worse.

I shall now pray every day for a vessel to come and carry me to my loved ones at home. God grant that it may be soon.

## Tuesday 21st March 1871 {#sec-volume-3-21-mar}

Today has been showery and rather cold.

The men did not seem over well pleased this morning. At breakfast they swore a great deal about the want of tea and sugar. I told them there was no hurry about clearing the road for a few days, consequently we would wait until the weather had settled. This seemed acceptable to them and they quietened down.
As a rule they don't swear much in my presence, but my room is so close to where they are living that I can always hear them, which makes it very unpleasant. I have got a very sore throat from the effects of my Gumshaew trip; I trust I will not have to visit that place again; we got [sic] a month's flour on hand yet. 

## Wednesday 22nd March 1871 {#sec-volume-3-22-mar}

This has been the warmest day we have had this year.
Where it not for the snow all around us I could believe summer had come, but the climate here amongst these mountains is very changeable.

I am quite lost now for the want of something to do. It is terrible work to be waiting and waiting with great anxiety. Could one go anywhere to see something new or take a little change it would be very different, but shut up as we are in this hole without the slightest change and unemployed is bad enough to think about, but something terrible to realize.

Sometimes I am so nervous that the slightest sound will make me start.

## Thursday 23rd March 1871 {#sec-volume-3-23-mar}

This has been another beautiful day.

We should have started to clear the lower tramway today, but the frost at night had made it so hard that it would be impossible to work the snow plow on it - and to do it by hand would be a good week's work, so I will wait a little until we get some more rains.

## Friday 24th March 1871 {#sec-volume-3-24-mar}

This has been a fearful day of wind and rain. One night here will change the weather from June to December.

Beauchamp gets up every day for a little now, but his leg is very weak. The knee seems to be the weakest part of it. Today he was foolish enough to try his weight on it. When it gave way and down he fell with it under him it was next to a miracle that it escaped being broken again, but he has hurt it bad enough to keep it back at least a couple of weeks. I wish a vessel would come in for his sake alone. I have had a trying time with him; he is so cross and ill natured that nothing can be done to please him - and as to advice, he won't take any.

## Saturday 25th March 1871 {#sec-volume-3-25-mar}

It has rained today without interruption; Enough to make one go crazy.

Two canoes arrived from Gold Harbor. They had been out on a hunting cruise and brought back twenty seal skins and a number of halibut. I bought one of these fish; it weighed 90 lbs when divested of the head and tail. They are most delicious fish and a very acceptable change from salt beef. The sealskins are worth $2.00 each, so that they have had a very remunerative  trip.

## Sunday 26th March 1871 {#sec-volume-3-26-mar}

We have had all sorts of weather today except fine: it has rained, sleeted, hailed and snowed.

I have been sorely depressed in spirits today. I had hoped to be on my way back to all I love by this time. But no! And how long we shall have to remain here yet it is impossible to tell. I am fully aware of the procrastinating ways of the Company and when I sit down and think about it, it makes me perfectly miserable.

No one but those who have experienced such a life as this can fully understand my feelings. If I could but spend another Sabbath with my dear ones, and I know they are as anxious as I am; bad as I have been; home will [sic] dull and lonely without me.

Laiken is fretting himself very much at being kept here over the time. He has 20 acres of land near Victoria for which he pays $120.00 a year rent. This will be a great loss to him, if he cannot get his crop in in time. Bad as the man has been, he has my full sympathy in this matter.
I am very unwell tonight. I feel quite feverish and lightheaded and a sore throat to boot; the wetting I got seems to stick to me.

## Monday 27th March 1871 {#sec-volume-3-27-mar}

The weather today has been somewhat like yesterday except an hour and a half in the afternoon. 

We tried to work the snow plow today, but the snow was too heavy.
I have been quite out of sorts again today. Godspeed the vessel if she is on the way for us.

## Tuesday 28th March 1871 {#sec-volume-3-28-mar}

Showers of sleet all day. 

Repaired a portion of the Tramway. The place is becoming quite hateful to me, and this hoping from day to day for something to come and fetch us, is most unbearable.

## Wednesday 29th March 1871 {#sec-volume-3-29-mar}

It has been raining heavens hard all day.

I feel too much depressed in spirits to think of anything to write. As for incidents, there are none.

## Thursday 30th March 1871 {#sec-volume-3-30-mar}

This has been a showery day, but rather mild.

The men are grumbling a great deal about being kept so long over their time, and talk to me as though I was the cause of the delay. I can sympathize with them, but cannot assist them as I am more anxious than they are.

## Friday 31st March 1871 {#sec-volume-3-31-mar}

This has been another day of rain. It has been pouring down as though a river had been let loose. 

A canoe came in from Skidegate this afternoon with information of Captain McKay's arrival at Gumshewa [sic]. Our flour is now nearly exhausted so McKay's arrival is good news, as I hope to hear from my darling by him, and I have some hope that he may be coming to take us away.

## Saturday 1st April 1871 {#sec-volume-3-1-apr}

This has been a charming fine day. 

The Indians made an April fool of me. About noon I started for Gumshewa, but when we reached Skidegate a canoe had just arrived from that place and McKay had not got in. Consequently it was useless for me to go further. The Indians at Skidegate fancied they heard a large gun and concluded McKay had arrived. 

I remained at Skidegate all night and was well entertained by the chief. His house is by far the best Indian tenement I have yet seen; it is about 40 feet long by about 30 feet wide, the two main beams of the house are about 18 inches in diameter. The boards which form the lining of the house are in one length, and about 3 1/2 feet wide. They appear to have been split out and hewn down to a uniform thickness by some rude tool. Each house has a large wooden pillar in front; some of these pillars are 50 feet high and most wonderfully carved displaying representations of most hideous looking monsters.
Captain Skidegate’s ‘stick’ is the highest, and has an eagle sitting on top with an axe in his mouth.

## Sunday 2nd April 1871 {#sec-volume-3-2-apr}

This has been another beautiful day. 

Did not sleep well last night, the boards of Captain Skidegate’s floor (although the floor of a chiefs house] was not softer than other boards. Mrs. Skidegate kindly offered me a bed, but I was afraid there might be some small animals about so I declined her kindness. In the morning she asked me how I had slept, and when I told her that I had not slept much owing to the hard floor she was very much disgusted that I had not accepted her offer the night before.

Left Skidegate at noon for Hastings. The men were very much disappointed on hearing that McKay had not arrived.

## Monday 3rd April 1871 {#sec-volume-3-3-apr}

The weather appears to have taken a change for the better, it has been such a lovely day, that one could almost fancy summer had set in.

I am beginning to think that things are not as they should be with the Company, otherwise they would have sent for us long ago. I have all along been looking forward to the 21st of March, hoping that that day or thereabouts would end my career here, but now I am fretting myself to death about the delay. I pray every night that the next day may bring something, but all in vain.

## Tuesday 4th April 1871 {#sec-volume-3-4-apr}

This has been quite a summer day; it has really been warm and cheering.

When I went to bed last night I lay for a long time thinking of my loved ones at home; and when I went to sleep, I was dreaming all night. I thought I was in Victoria, and walking where I could see the little house on Blanchard Street. I was on my way round to the front and, and on looking toward the back door I beheld my dear little Bobin with Aley and Kate standing on each side of him. He was in his baby dress of blue frock and white pinafore. I called to him, but Kate was the first to hear me. She took a hold of him and pointed towards me. When he saw me he clapped his little hands for joy. I tried to go and join them, but somehow or other I could not get [sic]. I hope that when the time does come when I am called away I will have no difficulty in joining him in that land of pure delight. Hitherto I have dreamt of him in sickness, but this time he was the very picture of health.

## Wednesday 5th April 1871 {#sec-volume-3-5-apr}

Change in the weather; it has been raining all day.

This waiting is dreadful work, I looked towards Skidegate 50 times in a day, hoping each time to see something coming; and I know my dear ones are as anxious as I am.

## Thursday 6th April 1871 {#sec-volume-3-6-apr}

This has been a showery day, but not very cold.

I cannot settle my mind to write or think about anything. When this dreadful suspense is to come to a close is more than I can tell, and the very thoughts of it makes me wretched.

## Friday 7th April 1871 {#sec-volume-3-7-apr}

This has been quite a fine day, warm and sunny.

The men bother my life out with their eternal growling. I am as anxious to get away as they are, and yet they continually keep on asking how are they to get away. I shall be truly glad when I can part company with them.

## Saturday 8th April 1871 {#sec-volume-3-8-apr}

The weather today has been somewhat like yesterday.

We go out every day now and dig clams. When properly cooked they are very nice, so much salt meat, and no sacrine[??] matter is not good. The clams are therefore very acceptable.

## Sunday 9th April 1871 {#sec-volume-3-9-apr}

Today for a wonder has been fine, we so seldom get a fine Sunday, that when it does come I can thoroughly appreciate it. 

## Monday 10th April 1871 {#sec-volume-3-10-apr}

The weather still keeps fine, which renders our condition a little more cheering: but we are now reduced a sack and a half of flour, and where I am to get more is a query. I have already had enough of canoe trips, yet we cannot do well without flour. For my own part, rather than make another canoe trip I would do without it some time, but the men are already deploring the prospect of our running out before anything comes to relieve us. Altogether I am truly disheartened and sincerely trust the end is not far off.

## Tuesday 11th April 1871 {#sec-volume-3-11-apr}

Today has been rather showering; we had a very heavy hail storm. The hailstones were as large as peas.

I have been in sad spirits today; the heavens are black and gloomy, so is all around me.

## Wednesday 12th April 1871 {#sec-volume-3-12-apr}

Today has been one continuous showering of hail and very cold.

This is indeed a most depressing climate, and the great want of cheerful association and a little change make it at times almost unbearable. Were it not for Beardsell I don't know what I should do. He at least looks at the matter in a reasonable manner and does not, like the others, try to make my life more miserable.

## Thursday 13th April 1871 {#sec-volume-3-13-apr}

We have had a little change in the weather today. Instead of hail it has been sleet and so raw and cold it feels as though winter was returning.

We are now reduced to our last sack of flour. Something will have to be done soon. The nearest place to get relief is Masset, which is about 130 miles from here, and from all I can learn a very dangerous coast. I sincerely hope I will not be compelled to make such a journey.

## Friday 14th April 1871 {#sec-volume-3-14-apr}

It has been sleeting again all day, truly miserable weather.

I cannot get rid of my sore throat. This kind of weather is very much against it. What would I not give to be at home with my darlings. I am becoming more and more homesick every day. I would make a bad sailor, to be continually leaving home.

## Saturday 15th April 1871 {#sec-volume-3-15-apr}

Sleet is still the order of the day. The trees at the mine are again covered with snow, the sleet down here has been snow up there.

Some Indians came in today with halibut, which was a great treat. This is truly a delicious fish. They brought quite a number of sealskins, some of them having as many as fifty. 

## Sunday 16th April 1871 {#sec-volume-3-16-apr}

Showers of hail and rain all day. 

I have now ceased to look upon these days as being truly Sabbaths; there is not the slightest change to mark them. I can easily understand a man in time (when shut out from all Sabbath association) becoming utterly regardless of the Sabbath, but thank God I have not yet come to that pass and I trust I never shall, but fretting as I am just now I cannot even compose myself to read. As soon as I begin, I find myself thinking about something else and forgetting altogether what I am reading about.

## Monday 17th April 1871 {#sec-volume-3-17-apr}

It has been showery all day, and raining heavens hard tonight. 

We have only flour now to last us until Saturday; consequently I will have to do something this week. If I go to Gumshaew the chances are I will have to come back empty, and as for going to Masset, I don't like the idea of it. I cannot understand what they can be thinking about in Victoria, knowing as they do that we had only six months provisions. Should we leave the place to the mercy of the Indians it would soon be demolished, yet we cannot live upon the wind. Something will have to be done soon.

## Tuesday 18th April 1871 {#sec-volume-3-18-apr}

When I went down to breakfast this morning, Rielly and Laiken began to blackguard me at a fearful rate. Laiken said that Gaston told him if we should run out of provisions that there would be no difficulty in procuring some, as there were two stores on the island now.
After breakfast Beardsell and Lamerie came to me and said if I would go to Masset they would accompany me. After thinking over the matter, I informed them that I would go so they might prepare to make a start after dinner.

