# Maps {#sec-maps}

## Passage of the sloop Thornton from Victoria to the Queen Charlotte islands (now called Haida Gwaii).

```{r}
#| echo: false
#| message: false
#| warning: false
library(leaflet)
library(sf)
library(dplyr)

# 1) Read the GeoJSON
pts <- st_read("geojson/skidegate_trip_up_points.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

lns <- st_read("geojson/skidegate_trip_up_paths.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

qcco <- st_read("geojson/qccco_places.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

whaling_stations <- st_read("geojson/whaling_stations.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

gold_harbour <- st_read("geojson/gold_harbour.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

haida_villages <- st_read("geojson/haida_villages.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

# 3) Leaflet map
m <- leaflet(options = leafletOptions(preferCanvas = TRUE)) %>%
  # Base groups
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "Positron (minimal)") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "World Imagery (satellite)") %>%

  # Overlay groups (name them so you can toggle)
  addPolylines(
    data = lns,
    group = "Skidegate Journey",
    color = "#f95d6a",
    weight = 2,
    opacity = 0.9,
    smoothFactor = 0.5
  ) %>%
  addCircleMarkers(
  data = pts,
  group = "Skidegate Journey Locations",
  radius = 5,
  stroke = TRUE,
  color = "black",     # outline colour
  weight = 1,          # thin line
  fillColor = "#ffa600",
  fillOpacity = 0.8,
  popup = ~Name,
  label = ~Name
  ) %>%
  addCircleMarkers(
  data = qcco,
  group = "QCCCO Places",
  radius = 5,
  stroke = TRUE,
  color = "black",     # outline colour
  weight = 1,          # thin line
  fillColor = "#bc5090",
  fillOpacity = 0.8,
  popup = ~Name,
  label = ~Name
  ) %>%
  addCircleMarkers(
    data = gold_harbour,
    group = "Gold Harbour Places",
    radius = 5,
    stroke = TRUE,
    color = "black",     # outline colour
    weight = 1,          # thin line
    fillColor = "#58508d",
    fillOpacity = 0.8,
    popup = ~Name,
    label = ~Name
    ) %>%
  addCircleMarkers(
    data = whaling_stations,
    group = "Whaling Stations",
    radius = 5,
    stroke = TRUE,
    color = "black",     # outline colour
    weight = 1,          # thin line
    fillColor = "#003f5c",
    fillOpacity = 0.8,
    popup = ~Name,
    label = ~Name
    ) %>%
  addCircleMarkers(
    data = haida_villages,
    group = "Haida Villages",
    radius = 5,
    stroke = TRUE,
    color = "black",     # outline colour
    weight = 1,          # thin line
    fillColor = "#2f4b7c",
    fillOpacity = 0.8,
    popup = ~Name,
    label = ~Name
    ) %>%
  addLayersControl(
    baseGroups = c("OSM (default)", "Positron (minimal)", "World Imagery (satellite)"),
    overlayGroups = c("Skidegate Journey", "Skidegate Journey Locations","QCCCO Places", "Gold Harbour Places","Whaling Stations","Haida Villages"),
    options = list(collapsed = FALSE)
  )

legend_html <- "
<div style='background: white; padding: 5px; border-radius: 4px'>
<b>Legend</b><br>
<div><svg width='12' height='12'>
<circle cx='6' cy='6' r='5' stroke='black' stroke-width='1' fill='#ffa600'/></svg>
 Skidegate Journey Locations</div>
<div><svg width='12' height='12'>
<circle cx='6' cy='6' r='5' stroke='black' stroke-width='1' fill='#bc5090'/></svg>
 QCCCO Places</div>
<div><svg width='12' height='12'>
<circle cx='6' cy='6' r='5' stroke='black' stroke-width='1' fill='#58508d'/></svg>
 Gold Harbour Places</div>
<div><svg width='12' height='12'>
<circle cx='6' cy='6' r='5' stroke='black' stroke-width='1' fill='#003f5c'/></svg>
 Whaling Stations</div>
<div><svg width='12' height='12'>
<circle cx='6' cy='6' r='5' stroke='black' stroke-width='1' fill='#2f4b7c'/></svg>
 Haida Villages</div>
</div>
"

m <- m %>%
  addControl(legend_html, position = "bottomleft")

m


```

## Canoe Trips

```{r}
#| echo: false
#| message: false
#| warning: false
library(leaflet)
library(sf)
library(dplyr)

# 1) Read the GeoJSON
cumshewa_out <- st_read("geojson/canoe_cumshewa_out_points.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

cumshewa_back <- st_read("geojson/canoe_cumshewa_back_points.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

masset_out <- st_read("geojson/canoe_masset_out_points.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

masset_back <- st_read("geojson/canoe_masset_back_points.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

cumshewa_path <- st_read("geojson/canoe_cumshewa_paths.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

masset_path <- st_read("geojson/canoe_masset_paths.geojson", quiet = TRUE) %>%
  select(Name) %>%
  st_transform(4326) %>%
  st_zm(drop = TRUE, what = "ZM")

# 3) Leaflet map
m <- leaflet(options = leafletOptions(preferCanvas = TRUE)) %>%
  # Base groups
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "Positron (minimal)") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "World Imagery (satellite)") %>%

  # Overlay groups (name them so you can toggle)
  addPolylines(
    data = cumshewa_path,
    group = "Cumshewa Canoe Journey",
    color = "#003f5c",
    weight = 2,
    opacity = 0.9,
    smoothFactor = 0.5
  ) %>%
  addPolylines(
    data = masset_path,
    group = "Masset Canoe Journey",
    color = "#665191",
    weight = 2,
    opacity = 0.9,
    smoothFactor = 0.5
  ) %>%
  addCircleMarkers(
  data = cumshewa_out,
  group = "Cumshewa Journey Out",
  radius = 5,
  stroke = TRUE,
  color = "black",     # outline colour
  weight = 1,          # thin line
  fillColor = "#ffa600",
  fillOpacity = 0.8,
  popup = ~Name,
  label = ~Name
  ) %>%
  addCircleMarkers(
  data = cumshewa_back,
  group = "Cumshewa Journey Back",
  radius = 5,
  stroke = TRUE,
  color = "black",     # outline colour
  weight = 1,          # thin line
  fillColor = "#f95d6a",
  fillOpacity = 0.8,
  popup = ~Name,
  label = ~Name
  ) %>%
  addCircleMarkers(
  data = masset_out,
  group = "Masset Journey Out",
  radius = 5,
  stroke = TRUE,
  color = "black",     # outline colour
  weight = 1,          # thin line
  fillColor = "#58508d",
  fillOpacity = 0.8,
  popup = ~Name,
  label = ~Name
  ) %>%
  addCircleMarkers(
  data = masset_back,
  group = "Masset Journey Back",
  radius = 5,
  stroke = TRUE,
  color = "black",     # outline colour
  weight = 1,          # thin line
  fillColor = "#d45087",
  fillOpacity = 0.8,
  popup = ~Name,
  label = ~Name
  ) %>%
  addLayersControl(
    baseGroups = c("OSM (default)", "Positron (minimal)", "World Imagery (satellite)"),
    overlayGroups = c("Cumshewa Canoe Journey", "Masset Canoe Journey", "Cumshewa Journey Out","Cumshewa Journey Back", "Masset Journey Out","Masset Journey Back"),
    options = list(collapsed = FALSE)
  )

legend_html <- "
<div style='background: white; padding: 5px; border-radius: 4px'>
<b>Legend</b><br>

<!-- Points -->
<div style='margin-top:8px;'>
  <svg width='12' height='12' style='vertical-align:middle;'>
    <circle cx='6' cy='6' r='5' stroke='black' stroke-width='1' fill='#ffa600'/>
  </svg>
  <span style='vertical-align:middle;'>Cumshewa Journey Out</span>
</div>

<div>
  <svg width='12' height='12' style='vertical-align:middle;'>
    <circle cx='6' cy='6' r='5' stroke='black' stroke-width='1' fill='#f95d6a'/>
  </svg>
  <span style='vertical-align:middle;'>Cumshewa Journey Back</span>
</div>

<div>
  <svg width='12' height='12' style='vertical-align:middle;'>
    <circle cx='6' cy='6' r='5' stroke='black' stroke-width='1' fill='#ff7c43'/>
  </svg>
  <span style='vertical-align:middle;'>Masset Journey Out</span>
</div>

<div>
  <svg width='12' height='12' style='vertical-align:middle;'>
    <circle cx='6' cy='6' r='5' stroke='black' stroke-width='1' fill='#d45087'/>
  </svg>
  <span style='vertical-align:middle;'>Masset Journey Back</span>
</div>

</div>
"

m <- m %>%
  addControl(legend_html, position = "bottomleft")

m


```
