# References {.unnumbered}

::: {#refs}
Dictionary of Canadian Biography. McKenzie, Kenneth. Volume X (1871-1880) <https://www.biographi.ca/en/bio/mckenzie_kenneth_10E.html>

Saanich Archives: Russell Family Fonds

BC Food History Network. Soda Water in B.C. <https://bcfoodhistory.ca/soda-water/>

Old Cemeteries Society of Victoria, British Columbia, Canada. History of Pioneer Square. <https://oldcem.bc.ca/cem/cem_pn/history/>

Michael, Alice née Russell. Undated. The Founding and Building up of Craigflower. Russell family, pers comm.

Stricker, Judith. 1983. Hallmark Heritage Society. Colonial Schoolmasters at Craigflower 1859-1870. <https://hallmarkheritagesociety.ca/archives/history-articles/colonial-schoolmasters-at-craigflower/>

Stricker, Judith. Thomas Russell – Biography by Judith Stricker. https://epe.lac-bac.gc.ca/100/205/301/ic/cdc/craigflower/farmfolk/russell2.html?nodisclaimer=1

Vancouver Island GenWeb Project. Ships list of passengers for the Norman Morison 1852 arrived Victoria in January 16 1853. <https://sites.rootsweb.com/~bcvancou/ships/nmor53.htm>

Ross Bay Cemetery Records

Geological Survey of Canada, Multicoloured Geological Map, 435. https://doi.org/10.4095/214731

Richardson J. 1873 Report on the Coal Fields of Vancouver and Queen Charlotte Islands with a map of the distribution of the former addressed to Alfred R.C. Selwyn, Esq., F.G.S. Director of the Geological Survey of Canada pages 57-61

Geological Survey of Canada & Commission géologique du Canada (1876). Map showing the localities of fossils collected by James Richardson in 1872, from the Queen Charlotte Islands. Geological Survey of Canada, Multicoloured Geological Map, 435. https://doi.org/10.4095/214731

Dawson, G.M. Report on the Queen Charlotte Islands in Geological Survey of Canada 1878-79 Report of Progress:

Sutherland Brown, A. 1968. Geology of the Queen Charlotte Islands British Columbia. British Columbia Department of Mines and Petroleum Resources Bulletin No. 54. 

Dawson, G.M. 1880. Queen Charlotte Islands. Geological Survey of Canada Report of Progress 1878-1879. 

Ells, R.W. 1906. Report on Graham Island British Columbia. Canada Department of Mines Geological Survey Branch Annual Report, New Series Volume 16 1904 Pt B. 
Reprint accessible at: https://unbc.arcabc.ca/books/196

Hyndman , R.D. 2015 Tectonics and Structure of the Queen Charlotte Fault Zone, Haida Gwaii, and Large Thrust Earthquakes.  Bulletin of the Seismological Society of America, Vol. 105, No. 2b, pp.

Leonard, L.J.  and Bednarski. J.M.  2015 The Preservation Potential of Coastal Coseismic and Tsunami Evidence Observed Following the 2012 Mw 7.8 Haida Gwaii Thrust Earthquake. Bulletin of the Seismological Society of America (2015) 105 (2B): 1280–1289

Sutherland Brown, A. 1968. Geology of the Queen Charlotte Islands British Columbia. British Columbia Department of Mines and Petroleum resources Bulletin No. 54. 226pp. 

https://ahgp.org/westcoast/west_coast_gazetteer_directory_victoria_british_columbia_canada.html

https://www.wikitree.com/wiki/Fawcett-2277

https://bccd.vpl.ca/1868/First_Victoria_Directory_2nd_Issue/jpeg/0023_Victoria_-_Names_Page_08.jpeg

https://search-collections.royalbcmuseum.bc.ca/Image/Genealogy/02afad5b-8896-4766-946f-d50e209233c8

Sources: Geological Survey of Canada Report on the Queen Charlotte islands 1878 by George M. Dawson in Geological Survey of Canada Report of Progress 1878-1879 p. 163B 
http://massetbc.com/visitors/old-massett/

Bush, W. 2021. Hunting History: On the trail of Len Clay’s Archive. Foghorn, Underwater Archaeological Society of British Columbia Volume 37, No. 2 pp 1 – 6.
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://uasbc.com/sites/default/files/foghorn-pdf/UASBC_2021_June_Summer.pdf

Clay, Elaine V. Seeking A Fortune - Alexander Dawson Donaldson. Explorer, trailblazer and pioneer.: A Historical Biography - A window in time that captures 19th century life in Victoria, British Columbia. Kindle books.

H.M.S. Grappler  https://www.nauticapedia.ca/dbase/Query/Shiplist5.php?&name=Grappler+%28II%29&id=32208&Page=1&input=grappler
http://historic-shipping.co.uk/monwigram/grapp%2056.html
https://en.wikipedia.org/wiki/HMS_Grappler_%281856%29

Merilees, W. 1985. The Humpback Whales of Georgia Strait. Journal of the Vancouver Aquarium Volume 8. Sharon Proctor, Ed. 25pp.
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://naturevancouver.ca/wp-content/uploads/2020/12/The-Humpback-Whales-of-Georgia-Strait-Journal-of-the-Vancouver-Aquarium-Volume-8-1985.pdf


:::
