# Rowland W. Fawcett {.unnumbered #sec-appendix-3}

Rowland Wignall Fawcett (1840 – 1912) was a member of a well know pioneer family in Victoria. He arrived in Victoria from San Francisco with his family (parents Thomas and Jane, sisters Louise and Amy, brothers Edgar, Arthur and Thomas) in February 1859. Rowland followed his father into trade as an upholsterer and paper hanger with an address on Government Street. His brother Edgar worked for a time as a clerk in Thomas Russell’s grocery store. See @sec-russell-business-tragedy for more details on Thomas Russell's grocery business. 

Rowland’s relationship to Thomas Russell is unknown – probably they were friends. Rowland died in Victoria of influenza on March 30th 1912 and is buried in Ross Bay Cemetery. Rowland’s brother Edgar is better known for authoring ‘_Some Reminiscences of Old Victoria_’ published in 1912.

## References

https://ahgp.org/westcoast/west_coast_gazetteer_directory_victoria_british_columbia_canada.html

https://www.wikitree.com/wiki/Fawcett-2277

https://bccd.vpl.ca/1868/First_Victoria_Directory_2nd_Issue/jpeg/0023_Victoria_-_Names_Page_08.jpeg

https://search-collections.royalbcmuseum.bc.ca/Image/Genealogy/02afad5b-8896-4766-946f-d50e209233c8