# Superintendents of the Cowgitz Mine {.unnumbered #sec-appendix}

Queen Charlotte Coal Mining Company Limited Mine Superintendents.

The following is a partial listing gleasned from various records.

### 1865

Robinson took over as Superintendent in October
	
### 1866

Robinson till mid January
	
??? from mid-January on?
  
### 1867

John Landale arrived 24th November and left 8th December - for inspection report? 

Unclear if he was acting as Superintendent.

### 1868

Superintendent unknown.
	
John Landale return date unknown: His 1868 Operations Report was written in August from Anchor Cove upon his apparent removal to Victoria that month.

### 1869

Superintendent uknown.
	
Mifflin Gibbs arrived as a contractor in January with 50 men to build a railway and wharves for shipping coal  
	
???? Stayed till arrival of John Landale?
	
John Landale ?acting as Superintendent to November
	
### 1870
	
Mr Trounce ?acting as Superintendent overseeing	construction of at least part of the tramway: Identified as 'Inspector of Contracts' by Russell.

Mr. Branch ?acting as Superintendent?
  
Thomas Russell as Superintendent from arrival in October

### 1871

Thomas Russell 'till departure in May when operations shut down.
